/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnBcProg.java
 * 日 期：Tue Aug 02 20:42:05 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_BC_PROG", keyGenerator = "uuid")
public class PpnBcProg implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AFD_FLAG = "AFD_FLAG";
	public static String PROP_AUDIO_LANG_CODE = "AUDIO_LANG_CODE";
	public static String PROP_AUDIO_LANG_NAME = "AUDIO_LANG_NAME";
	public static String PROP_AUDIO_TYPE = "AUDIO_TYPE";
	public static String PROP_MEDIA_TYPE = "MEDIA_TYPE";
	public static String PROP_NEWS_FLAG = "NEWS_FLAG";
	public static String PROP_PROG_CODE = "PROG_CODE";
	public static String PROP_PROG_CREATE_TIME = "PROG_CREATE_TIME";
	public static String PROP_PROG_DESC = "PROG_DESC";
	public static String PROP_PROG_DURATION = "PROG_DURATION";
	public static String PROP_PROG_FIELD1 = "PROG_FIELD1";
	public static String PROP_PROG_FIELD2 = "PROG_FIELD2";
	public static String PROP_PROG_ID = "PROG_ID";
	public static String PROP_PROG_NAME = "PROG_NAME";
	public static String PROP_PROG_SEGMENT_SUM = "PROG_SEGMENT_SUM";
	public static String PROP_SUBTITLE_LANG_CODE = "SUBTITLE_LANG_CODE";
	public static String PROP_SUBTITLE_LANG_NAME = "SUBTITLE_LANG_NAME";
	public static String PROP_VIDEO_TYPE = "VIDEO_TYPE";
	
	/** primary key field of progId */
	@FieldMapping(columnName = "PROG_ID", columnType = 12, primary = true)
	private String progId;
	@FieldMapping(columnName = "AFD_FLAG", columnType = 2)
	private Integer afdFlag;
	@FieldMapping(columnName = "AUDIO_LANG_CODE", columnType = 12)
	private String audioLangCode;
	@FieldMapping(columnName = "AUDIO_LANG_NAME", columnType = 12)
	private String audioLangName;
	@FieldMapping(columnName = "AUDIO_TYPE", columnType = 2)
	private Integer audioType;
	@FieldMapping(columnName = "MEDIA_TYPE", columnType = 2)
	private Integer mediaType;
	@FieldMapping(columnName = "NEWS_FLAG", columnType = 2)
	private Integer newsFlag;
	@FieldMapping(columnName = "PROG_CODE", columnType = 12)
	private String progCode;
	@FieldMapping(columnName = "PROG_CREATE_TIME", columnType = 93)
	private Date progCreateTime;
	@FieldMapping(columnName = "PROG_DESC", columnType = 12)
	private String progDesc;
	@FieldMapping(columnName = "PROG_DURATION", columnType = 12)
	private String progDuration;
	@FieldMapping(columnName = "PROG_FIELD1", columnType = 12)
	private String progField1;
	@FieldMapping(columnName = "PROG_FIELD2", columnType = 12)
	private String progField2;
	@FieldMapping(columnName = "PROG_NAME", columnType = 12)
	private String progName;
	@FieldMapping(columnName = "PROG_SEGMENT_SUM", columnType = 12)
	private String progSegmentSum;
	@FieldMapping(columnName = "SUBTITLE_LANG_CODE", columnType = 12)
	private String subtitleLangCode;
	@FieldMapping(columnName = "SUBTITLE_LANG_NAME", columnType = 12)
	private String subtitleLangName;
	@FieldMapping(columnName = "VIDEO_TYPE", columnType = 2)
	private Integer videoType;
	
	public PpnBcProg() {
		super();
	}

	public PpnBcProg(String progId) {
		this.progId = progId;
	}

	public PpnBcProg(String audioLangCode, String progCode, String progDuration, String progName) {
		this.audioLangCode = audioLangCode;
		this.progCode = progCode;
		this.progDuration = progDuration;
		this.progName = progName;
	}

	/**
	 * @return the afdFlag
	 */
	public Integer getAfdFlag() {
		return this.afdFlag;
	}
	
	/**
	 * @param afdFlag the afdFlag to set
	 */
	public void setAfdFlag(Integer value) {
		this.afdFlag = value;
	}

	/**
	 * @return the audioLangCode
	 */
	public String getAudioLangCode() {
		return this.audioLangCode;
	}
	
	/**
	 * @param audioLangCode the audioLangCode to set
	 */
	public void setAudioLangCode(String value) {
		this.audioLangCode = value;
	}

	/**
	 * @return the audioLangName
	 */
	public String getAudioLangName() {
		return this.audioLangName;
	}
	
	/**
	 * @param audioLangName the audioLangName to set
	 */
	public void setAudioLangName(String value) {
		this.audioLangName = value;
	}

	/**
	 * @return the audioType
	 */
	public Integer getAudioType() {
		return this.audioType;
	}
	
	/**
	 * @param audioType the audioType to set
	 */
	public void setAudioType(Integer value) {
		this.audioType = value;
	}

	/**
	 * @return the mediaType
	 */
	public Integer getMediaType() {
		return this.mediaType;
	}
	
	/**
	 * @param mediaType the mediaType to set
	 */
	public void setMediaType(Integer value) {
		this.mediaType = value;
	}

	/**
	 * @return the newsFlag
	 */
	public Integer getNewsFlag() {
		return this.newsFlag;
	}
	
	/**
	 * @param newsFlag the newsFlag to set
	 */
	public void setNewsFlag(Integer value) {
		this.newsFlag = value;
	}

	/**
	 * @return the progCode
	 */
	public String getProgCode() {
		return this.progCode;
	}
	
	/**
	 * @param progCode the progCode to set
	 */
	public void setProgCode(String value) {
		this.progCode = value;
	}

	/**
	 * @return the progCreateTime
	 */
	public Date getProgCreateTime() {
		return this.progCreateTime;
	}
	
	/**
	 * @param progCreateTime the progCreateTime to set
	 */
	public void setProgCreateTime(Date value) {
		this.progCreateTime = value;
	}

	/**
	 * @return the progDesc
	 */
	public String getProgDesc() {
		return this.progDesc;
	}
	
	/**
	 * @param progDesc the progDesc to set
	 */
	public void setProgDesc(String value) {
		this.progDesc = value;
	}

	/**
	 * @return the progDuration
	 */
	public String getProgDuration() {
		return this.progDuration;
	}
	
	/**
	 * @param progDuration the progDuration to set
	 */
	public void setProgDuration(String value) {
		this.progDuration = value;
	}

	/**
	 * @return the progField1
	 */
	public String getProgField1() {
		return this.progField1;
	}
	
	/**
	 * @param progField1 the progField1 to set
	 */
	public void setProgField1(String value) {
		this.progField1 = value;
	}

	/**
	 * @return the progField2
	 */
	public String getProgField2() {
		return this.progField2;
	}
	
	/**
	 * @param progField2 the progField2 to set
	 */
	public void setProgField2(String value) {
		this.progField2 = value;
	}

	/**
	 * @return the progId
	 */
	public String getProgId() {
		return this.progId;
	}
	
	/**
	 * @param progId the progId to set
	 */
	public void setProgId(String value) {
		this.progId = value;
	}

	/**
	 * @return the progName
	 */
	public String getProgName() {
		return this.progName;
	}
	
	/**
	 * @param progName the progName to set
	 */
	public void setProgName(String value) {
		this.progName = value;
	}

	/**
	 * @return the progSegmentSum
	 */
	public String getProgSegmentSum() {
		return this.progSegmentSum;
	}
	
	/**
	 * @param progSegmentSum the progSegmentSum to set
	 */
	public void setProgSegmentSum(String value) {
		this.progSegmentSum = value;
	}

	/**
	 * @return the subtitleLangCode
	 */
	public String getSubtitleLangCode() {
		return this.subtitleLangCode;
	}
	
	/**
	 * @param subtitleLangCode the subtitleLangCode to set
	 */
	public void setSubtitleLangCode(String value) {
		this.subtitleLangCode = value;
	}

	/**
	 * @return the subtitleLangName
	 */
	public String getSubtitleLangName() {
		return this.subtitleLangName;
	}
	
	/**
	 * @param subtitleLangName the subtitleLangName to set
	 */
	public void setSubtitleLangName(String value) {
		this.subtitleLangName = value;
	}

	/**
	 * @return the videoType
	 */
	public Integer getVideoType() {
		return this.videoType;
	}
	
	/**
	 * @param videoType the videoType to set
	 */
	public void setVideoType(Integer value) {
		this.videoType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnBcProg)) {
			return false;
		}
		PpnBcProg other = (PpnBcProg)o;
		if (null == this.progId) {
			if (other.progId != null)
				return false;
		} else if (!this.progId.equals(other.progId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((progId == null) ? 0 : progId.hashCode());
		return result;
	}
	
}