/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.bean.PpnBcItem.java
 * 日 期：Fri Jul 22 10:30:43 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_BC_ITEM", keyGenerator = "uuid")
public class PpnBcItem implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AD_ID = "AD_ID";
	public static String PROP_COLUMN_CODE = "COLUMN_CODE";
	public static String PROP_COLUMN_NAME = "COLUMN_NAME";
	public static String PROP_COLUMN_PLAY_PLAN_CODE = "COLUMN_PLAY_PLAN_CODE";
	public static String PROP_CTRL_ID = "CTRL_ID";
	public static String PROP_DEV_ID = "DEV_ID";
	public static String PROP_ITEM_AD_FLAG = "ITEM_AD_FLAG";
	public static String PROP_ITEM_CODE = "ITEM_CODE";
	public static String PROP_ITEM_COMMENT = "ITEM_COMMENT";
	public static String PROP_ITEM_CREATE_SYS = "ITEM_CREATE_SYS";
	public static String PROP_ITEM_CREATE_TIME = "ITEM_CREATE_TIME";
	public static String PROP_ITEM_CREATE_USER = "ITEM_CREATE_USER";
	public static String PROP_ITEM_DESC = "ITEM_DESC";
	public static String PROP_ITEM_DURATION = "ITEM_DURATION";
	public static String PROP_ITEM_FIELD1 = "ITEM_FIELD1";
	public static String PROP_ITEM_FIELD2 = "ITEM_FIELD2";
	public static String PROP_ITEM_ID = "ITEM_ID";
	public static String PROP_ITEM_INDEX = "ITEM_INDEX";
	public static String PROP_ITEM_PACK_CODE = "ITEM_PACK_CODE";
	public static String PROP_ITEM_PACK_FLAG = "ITEM_PACK_FLAG";
	public static String PROP_ITEM_PARENT_CODE = "ITEM_PARENT_CODE";
	public static String PROP_ITEM_PLAY_STATUS = "ITEM_PLAY_STATUS";
	public static String PROP_ITEM_PLAY_TIME = "ITEM_PLAY_TIME";
	public static String PROP_ITEM_STATUS = "ITEM_STATUS";
	public static String PROP_ITEM_SUPERVISION = "ITEM_SUPERVISION";
	public static String PROP_LIST_ID = "LIST_ID";
	public static String PROP_MEDIA_ID = "MEDIA_ID";
	public static String PROP_PROG_ID = "PROG_ID";
	
	/** primary key field of itemId */
	@FieldMapping(columnName = "ITEM_ID", columnType = 12, primary = true)
	private String itemId;
	/** foreign key field of PPN_BC_ITEM_AD.AD_ID */
	@FieldMapping(columnName = "AD_ID", columnType = 12)
	private String adId;
	@FieldMapping(columnName = "COLUMN_CODE", columnType = 12)
	private String columnCode;
	@FieldMapping(columnName = "COLUMN_NAME", columnType = 12)
	private String columnName;
	@FieldMapping(columnName = "COLUMN_PLAY_PLAN_CODE", columnType = 12)
	private String columnPlayPlanCode;
	/** foreign key field of PPN_BC_ITEM_CTRL.CTRL_ID */
	@FieldMapping(columnName = "CTRL_ID", columnType = 12)
	private String ctrlId;
	/** foreign key field of PPN_BC_ITEM_PLAY_DEV.DEV_ID */
	@FieldMapping(columnName = "DEV_ID", columnType = 12)
	private String devId;
	@FieldMapping(columnName = "ITEM_AD_FLAG", columnType = 2)
	private Integer itemAdFlag;
	@FieldMapping(columnName = "ITEM_CODE", columnType = 12)
	private String itemCode;
	@FieldMapping(columnName = "ITEM_COMMENT", columnType = 12)
	private String itemComment;
	@FieldMapping(columnName = "ITEM_CREATE_SYS", columnType = 12)
	private String itemCreateSys;
	@FieldMapping(columnName = "ITEM_CREATE_TIME", columnType = 93)
	private Date itemCreateTime;
	@FieldMapping(columnName = "ITEM_CREATE_USER", columnType = 12)
	private String itemCreateUser;
	@FieldMapping(columnName = "ITEM_DESC", columnType = 12)
	private String itemDesc;
	@FieldMapping(columnName = "ITEM_DURATION", columnType = 12)
	private String itemDuration;
	@FieldMapping(columnName = "ITEM_FIELD1", columnType = 12)
	private String itemField1;
	@FieldMapping(columnName = "ITEM_FIELD2", columnType = 12)
	private String itemField2;
	@FieldMapping(columnName = "ITEM_INDEX", columnType = 2)
	private Integer itemIndex;
	@FieldMapping(columnName = "ITEM_PACK_CODE", columnType = 12)
	private String itemPackCode;
	@FieldMapping(columnName = "ITEM_PACK_FLAG", columnType = 2)
	private Integer itemPackFlag;
	@FieldMapping(columnName = "ITEM_PARENT_CODE", columnType = 12)
	private String itemParentCode;
	@FieldMapping(columnName = "ITEM_PLAY_STATUS", columnType = 2)
	private Integer itemPlayStatus;
	@FieldMapping(columnName = "ITEM_PLAY_TIME", columnType = 12)
	private String itemPlayTime;
	@FieldMapping(columnName = "ITEM_STATUS", columnType = 2)
	private Integer itemStatus;
	@FieldMapping(columnName = "ITEM_SUPERVISION", columnType = 12)
	private String itemSupervision;
	/** foreign key field of PPN_BC_LIST.LIST_ID */
	@FieldMapping(columnName = "LIST_ID", columnType = 12)
	private String listId;
	/** foreign key field of PPN_BC_ITEM_MEDIA.MEDIA_ID */
	@FieldMapping(columnName = "MEDIA_ID", columnType = 12)
	private String mediaId;
	/** foreign key field of PPN_BC_PROG.PROG_ID */
	@FieldMapping(columnName = "PROG_ID", columnType = 12)
	private String progId;
	
	public PpnBcItem() {
		super();
	}

	public PpnBcItem(String itemId) {
		this.itemId = itemId;
	}

	public PpnBcItem(String columnCode, String itemCode, String itemDuration, Integer itemIndex, Integer itemPackFlag, String itemPlayTime) {
		this.columnCode = columnCode;
		this.itemCode = itemCode;
		this.itemDuration = itemDuration;
		this.itemIndex = itemIndex;
		this.itemPackFlag = itemPackFlag;
		this.itemPlayTime = itemPlayTime;
	}

	/**
	 * @return the adId
	 */
	public String getAdId() {
		return this.adId;
	}
	
	/**
	 * @param adId the adId to set
	 */
	public void setAdId(String value) {
		this.adId = value;
	}

	/**
	 * @return the columnCode
	 */
	public String getColumnCode() {
		return this.columnCode;
	}
	
	/**
	 * @param columnCode the columnCode to set
	 */
	public void setColumnCode(String value) {
		this.columnCode = value;
	}

	/**
	 * @return the columnName
	 */
	public String getColumnName() {
		return this.columnName;
	}
	
	/**
	 * @param columnName the columnName to set
	 */
	public void setColumnName(String value) {
		this.columnName = value;
	}

	/**
	 * @return the columnPlayPlanCode
	 */
	public String getColumnPlayPlanCode() {
		return this.columnPlayPlanCode;
	}
	
	/**
	 * @param columnPlayPlanCode the columnPlayPlanCode to set
	 */
	public void setColumnPlayPlanCode(String value) {
		this.columnPlayPlanCode = value;
	}

	/**
	 * @return the ctrlId
	 */
	public String getCtrlId() {
		return this.ctrlId;
	}
	
	/**
	 * @param ctrlId the ctrlId to set
	 */
	public void setCtrlId(String value) {
		this.ctrlId = value;
	}

	/**
	 * @return the devId
	 */
	public String getDevId() {
		return this.devId;
	}
	
	/**
	 * @param devId the devId to set
	 */
	public void setDevId(String value) {
		this.devId = value;
	}

	/**
	 * @return the itemAdFlag
	 */
	public Integer getItemAdFlag() {
		return this.itemAdFlag;
	}
	
	/**
	 * @param itemAdFlag the itemAdFlag to set
	 */
	public void setItemAdFlag(Integer value) {
		this.itemAdFlag = value;
	}

	/**
	 * @return the itemCode
	 */
	public String getItemCode() {
		return this.itemCode;
	}
	
	/**
	 * @param itemCode the itemCode to set
	 */
	public void setItemCode(String value) {
		this.itemCode = value;
	}

	/**
	 * @return the itemComment
	 */
	public String getItemComment() {
		return this.itemComment;
	}
	
	/**
	 * @param itemComment the itemComment to set
	 */
	public void setItemComment(String value) {
		this.itemComment = value;
	}

	/**
	 * @return the itemCreateSys
	 */
	public String getItemCreateSys() {
		return this.itemCreateSys;
	}
	
	/**
	 * @param itemCreateSys the itemCreateSys to set
	 */
	public void setItemCreateSys(String value) {
		this.itemCreateSys = value;
	}

	/**
	 * @return the itemCreateTime
	 */
	public Date getItemCreateTime() {
		return this.itemCreateTime;
	}
	
	/**
	 * @param itemCreateTime the itemCreateTime to set
	 */
	public void setItemCreateTime(Date value) {
		this.itemCreateTime = value;
	}

	/**
	 * @return the itemCreateUser
	 */
	public String getItemCreateUser() {
		return this.itemCreateUser;
	}
	
	/**
	 * @param itemCreateUser the itemCreateUser to set
	 */
	public void setItemCreateUser(String value) {
		this.itemCreateUser = value;
	}

	/**
	 * @return the itemDesc
	 */
	public String getItemDesc() {
		return this.itemDesc;
	}
	
	/**
	 * @param itemDesc the itemDesc to set
	 */
	public void setItemDesc(String value) {
		this.itemDesc = value;
	}

	/**
	 * @return the itemDuration
	 */
	public String getItemDuration() {
		return this.itemDuration;
	}
	
	/**
	 * @param itemDuration the itemDuration to set
	 */
	public void setItemDuration(String value) {
		this.itemDuration = value;
	}

	/**
	 * @return the itemField1
	 */
	public String getItemField1() {
		return this.itemField1;
	}
	
	/**
	 * @param itemField1 the itemField1 to set
	 */
	public void setItemField1(String value) {
		this.itemField1 = value;
	}

	/**
	 * @return the itemField2
	 */
	public String getItemField2() {
		return this.itemField2;
	}
	
	/**
	 * @param itemField2 the itemField2 to set
	 */
	public void setItemField2(String value) {
		this.itemField2 = value;
	}

	/**
	 * @return the itemId
	 */
	public String getItemId() {
		return this.itemId;
	}
	
	/**
	 * @param itemId the itemId to set
	 */
	public void setItemId(String value) {
		this.itemId = value;
	}

	/**
	 * @return the itemIndex
	 */
	public Integer getItemIndex() {
		return this.itemIndex;
	}
	
	/**
	 * @param itemIndex the itemIndex to set
	 */
	public void setItemIndex(Integer value) {
		this.itemIndex = value;
	}

	/**
	 * @return the itemPackCode
	 */
	public String getItemPackCode() {
		return this.itemPackCode;
	}
	
	/**
	 * @param itemPackCode the itemPackCode to set
	 */
	public void setItemPackCode(String value) {
		this.itemPackCode = value;
	}

	/**
	 * @return the itemPackFlag
	 */
	public Integer getItemPackFlag() {
		return this.itemPackFlag;
	}
	
	/**
	 * @param itemPackFlag the itemPackFlag to set
	 */
	public void setItemPackFlag(Integer value) {
		this.itemPackFlag = value;
	}

	/**
	 * @return the itemParentCode
	 */
	public String getItemParentCode() {
		return this.itemParentCode;
	}
	
	/**
	 * @param itemParentCode the itemParentCode to set
	 */
	public void setItemParentCode(String value) {
		this.itemParentCode = value;
	}

	/**
	 * @return the itemPlayStatus
	 */
	public Integer getItemPlayStatus() {
		return this.itemPlayStatus;
	}
	
	/**
	 * @param itemPlayStatus the itemPlayStatus to set
	 */
	public void setItemPlayStatus(Integer value) {
		this.itemPlayStatus = value;
	}

	/**
	 * @return the itemPlayTime
	 */
	public String getItemPlayTime() {
		return this.itemPlayTime;
	}
	
	/**
	 * @param itemPlayTime the itemPlayTime to set
	 */
	public void setItemPlayTime(String value) {
		this.itemPlayTime = value;
	}

	/**
	 * @return the itemStatus
	 */
	public Integer getItemStatus() {
		return this.itemStatus;
	}
	
	/**
	 * @param itemStatus the itemStatus to set
	 */
	public void setItemStatus(Integer value) {
		this.itemStatus = value;
	}

	/**
	 * @return the itemSupervision
	 */
	public String getItemSupervision() {
		return this.itemSupervision;
	}
	
	/**
	 * @param itemSupervision the itemSupervision to set
	 */
	public void setItemSupervision(String value) {
		this.itemSupervision = value;
	}

	/**
	 * @return the listId
	 */
	public String getListId() {
		return this.listId;
	}
	
	/**
	 * @param listId the listId to set
	 */
	public void setListId(String value) {
		this.listId = value;
	}

	/**
	 * @return the mediaId
	 */
	public String getMediaId() {
		return this.mediaId;
	}
	
	/**
	 * @param mediaId the mediaId to set
	 */
	public void setMediaId(String value) {
		this.mediaId = value;
	}

	/**
	 * @return the progId
	 */
	public String getProgId() {
		return this.progId;
	}
	
	/**
	 * @param progId the progId to set
	 */
	public void setProgId(String value) {
		this.progId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnBcItem)) {
			return false;
		}
		PpnBcItem other = (PpnBcItem)o;
		if (null == this.itemId) {
			if (other.itemId != null)
				return false;
		} else if (!this.itemId.equals(other.itemId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}
	
}