/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnBusinessword.java
 * 日 期：Wed Jul 20 16:11:14 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_BUSINESSWORD", keyGenerator = "uuid")
public class PpnBusinessword implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_BWORD_DATA = "BWORD_DATA";
	public static String PROP_BWORD_DESC = "BWORD_DESC";
	public static String PROP_BWORD_ID = "BWORD_ID";
	public static String PROP_BWORD_NAME = "BWORD_NAME";
	public static String PROP_BWORD_PARENTID = "BWORD_PARENTID";
	public static String PROP_BWORD_STATUS = "BWORD_STATUS";
	public static String PROP_BWORD_TYPE = "BWORD_TYPE";
	
	/** primary key field of bwordId */
	@FieldMapping(columnName = "BWORD_ID", columnType = 2, primary = true)
	private Long bwordId;
	@FieldMapping(columnName = "BWORD_DATA", columnType = 12)
	private String bwordData;
	@FieldMapping(columnName = "BWORD_DESC", columnType = 12)
	private String bwordDesc;
	@FieldMapping(columnName = "BWORD_NAME", columnType = 12)
	private String bwordName;
	@FieldMapping(columnName = "BWORD_PARENTID", columnType = 2)
	private Integer bwordParentid;
	@FieldMapping(columnName = "BWORD_STATUS", columnType = 2)
	private Integer bwordStatus;
	@FieldMapping(columnName = "BWORD_TYPE", columnType = 12)
	private String bwordType;
	
	public PpnBusinessword() {
		super();
	}

	public PpnBusinessword(Long bwordId) {
		this.bwordId = bwordId;
	}

	public PpnBusinessword(String bwordData, String bwordName, Integer bwordParentid, Integer bwordStatus, String bwordType) {
		this.bwordData = bwordData;
		this.bwordName = bwordName;
		this.bwordParentid = bwordParentid;
		this.bwordStatus = bwordStatus;
		this.bwordType = bwordType;
	}

	/**
	 * @return the bwordData
	 */
	public String getBwordData() {
		return this.bwordData;
	}
	
	/**
	 * @param bwordData the bwordData to set
	 */
	public void setBwordData(String value) {
		this.bwordData = value;
	}

	/**
	 * @return the bwordDesc
	 */
	public String getBwordDesc() {
		return this.bwordDesc;
	}
	
	/**
	 * @param bwordDesc the bwordDesc to set
	 */
	public void setBwordDesc(String value) {
		this.bwordDesc = value;
	}

	/**
	 * @return the bwordId
	 */
	public Long getBwordId() {
		return this.bwordId;
	}
	
	/**
	 * @param bwordId the bwordId to set
	 */
	public void setBwordId(Long value) {
		this.bwordId = value;
	}

	/**
	 * @return the bwordName
	 */
	public String getBwordName() {
		return this.bwordName;
	}
	
	/**
	 * @param bwordName the bwordName to set
	 */
	public void setBwordName(String value) {
		this.bwordName = value;
	}

	/**
	 * @return the bwordParentid
	 */
	public Integer getBwordParentid() {
		return this.bwordParentid;
	}
	
	/**
	 * @param bwordParentid the bwordParentid to set
	 */
	public void setBwordParentid(Integer value) {
		this.bwordParentid = value;
	}

	/**
	 * @return the bwordStatus
	 */
	public Integer getBwordStatus() {
		return this.bwordStatus;
	}
	
	/**
	 * @param bwordStatus the bwordStatus to set
	 */
	public void setBwordStatus(Integer value) {
		this.bwordStatus = value;
	}

	/**
	 * @return the bwordType
	 */
	public String getBwordType() {
		return this.bwordType;
	}
	
	/**
	 * @param bwordType the bwordType to set
	 */
	public void setBwordType(String value) {
		this.bwordType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnBusinessword)) {
			return false;
		}
		PpnBusinessword other = (PpnBusinessword)o;
		if (null == this.bwordId) {
			if (other.bwordId != null)
				return false;
		} else if (!this.bwordId.equals(other.bwordId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bwordId == null) ? 0 : bwordId.hashCode());
		return result;
	}
	
}