/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.bean.PpnBcItemAd.java
 * 日 期：Fri Jul 22 12:29:36 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_BC_ITEM_AD", keyGenerator = "uuid")
public class PpnBcItemAd implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AD_DESC = "AD_DESC";
	public static String PROP_AD_DURATION = "AD_DURATION";
	public static String PROP_AD_FIELD1 = "AD_FIELD1";
	public static String PROP_AD_FIELD2 = "AD_FIELD2";
	public static String PROP_AD_ID = "AD_ID";
	public static String PROP_AD_IS_AD = "AD_IS_AD";
	public static String PROP_AD_LIMIT_SUM = "AD_LIMIT_SUM";
	public static String PROP_AD_SEGMENT_CODE = "AD_SEGMENT_CODE";
	
	/** primary key field of adId */
	@FieldMapping(columnName = "AD_ID", columnType = 12, primary = true)
	private String adId;
	@FieldMapping(columnName = "AD_DESC", columnType = 12)
	private String adDesc;
	@FieldMapping(columnName = "AD_DURATION", columnType = 12)
	private String adDuration;
	@FieldMapping(columnName = "AD_FIELD1", columnType = 12)
	private String adField1;
	@FieldMapping(columnName = "AD_FIELD2", columnType = 12)
	private String adField2;
	@FieldMapping(columnName = "AD_IS_AD", columnType = 12)
	private String adIsAd;
	@FieldMapping(columnName = "AD_LIMIT_SUM", columnType = 2)
	private Integer adLimitSum;
	@FieldMapping(columnName = "AD_SEGMENT_CODE", columnType = 12)
	private String adSegmentCode;
	
	public PpnBcItemAd() {
		super();
	}

	public PpnBcItemAd(String adId) {
		this.adId = adId;
	}

	/**
	 * @return the adDesc
	 */
	public String getAdDesc() {
		return this.adDesc;
	}
	
	/**
	 * @param adDesc the adDesc to set
	 */
	public void setAdDesc(String value) {
		this.adDesc = value;
	}

	/**
	 * @return the adDuration
	 */
	public String getAdDuration() {
		return this.adDuration;
	}
	
	/**
	 * @param adDuration the adDuration to set
	 */
	public void setAdDuration(String value) {
		this.adDuration = value;
	}

	/**
	 * @return the adField1
	 */
	public String getAdField1() {
		return this.adField1;
	}
	
	/**
	 * @param adField1 the adField1 to set
	 */
	public void setAdField1(String value) {
		this.adField1 = value;
	}

	/**
	 * @return the adField2
	 */
	public String getAdField2() {
		return this.adField2;
	}
	
	/**
	 * @param adField2 the adField2 to set
	 */
	public void setAdField2(String value) {
		this.adField2 = value;
	}

	/**
	 * @return the adId
	 */
	public String getAdId() {
		return this.adId;
	}
	
	/**
	 * @param adId the adId to set
	 */
	public void setAdId(String value) {
		this.adId = value;
	}

	/**
	 * @return the adIsAd
	 */
	public String getAdIsAd() {
		return this.adIsAd;
	}
	
	/**
	 * @param adIsAd the adIsAd to set
	 */
	public void setAdIsAd(String value) {
		this.adIsAd = value;
	}

	/**
	 * @return the adLimitSum
	 */
	public Integer getAdLimitSum() {
		return this.adLimitSum;
	}
	
	/**
	 * @param adLimitSum the adLimitSum to set
	 */
	public void setAdLimitSum(Integer value) {
		this.adLimitSum = value;
	}

	/**
	 * @return the adSegmentCode
	 */
	public String getAdSegmentCode() {
		return this.adSegmentCode;
	}
	
	/**
	 * @param adSegmentCode the adSegmentCode to set
	 */
	public void setAdSegmentCode(String value) {
		this.adSegmentCode = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnBcItemAd)) {
			return false;
		}
		PpnBcItemAd other = (PpnBcItemAd)o;
		if (null == this.adId) {
			if (other.adId != null)
				return false;
		} else if (!this.adId.equals(other.adId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adId == null) ? 0 : adId.hashCode());
		return result;
	}
	
}