/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.bean.PpnCtlword.java
 * 日 期：Wed Nov 19 14:17:52 CST 2014
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.sql.Timestamp;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_CTLWORD", keyGenerator = "uuid")
public class PpnCtlword implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CW_CREATETIME = "CW_CREATETIME";
	public static String PROP_CW_DATA = "CW_DATA";
	public static String PROP_CW_DESC = "CW_DESC";
	public static String PROP_CW_FIELDALIAS = "CW_FIELDALIAS";
	public static String PROP_CW_FIELDNAME = "CW_FIELDNAME";
	public static String PROP_CW_ID = "CW_ID";
	public static String PROP_CW_NAME = "CW_NAME";
	public static String PROP_CW_PARENTID = "CW_PARENTID";
	public static String PROP_CW_STATUS = "CW_STATUS";
	public static String PROP_CW_TABLEALIAS = "CW_TABLEALIAS";
	public static String PROP_CW_TABLENAME = "CW_TABLENAME";
	public static String PROP_CW_TYPE = "CW_TYPE";
	
	/** primary key field of cwId */
	@FieldMapping(columnName = "CW_ID", columnType = 12, primary = true)
	private String cwId;
	@FieldMapping(columnName = "CW_CREATETIME", columnType = 93)
	private Timestamp cwCreatetime;
	@FieldMapping(columnName = "CW_DATA", columnType = 12)
	private String cwData;
	@FieldMapping(columnName = "CW_DESC", columnType = 12)
	private String cwDesc;
	@FieldMapping(columnName = "CW_FIELDALIAS", columnType = 12)
	private String cwFieldalias;
	@FieldMapping(columnName = "CW_FIELDNAME", columnType = 12)
	private String cwFieldname;
	@FieldMapping(columnName = "CW_NAME", columnType = 12)
	private String cwName;
	@FieldMapping(columnName = "CW_PARENTID", columnType = 12)
	private String cwParentid;
	@FieldMapping(columnName = "CW_STATUS", columnType = 2)
	private Integer cwStatus;
	@FieldMapping(columnName = "CW_TABLEALIAS", columnType = 12)
	private String cwTablealias;
	@FieldMapping(columnName = "CW_TABLENAME", columnType = 12)
	private String cwTablename;
	@FieldMapping(columnName = "CW_TYPE", columnType = 2)
	private Integer cwType;
	
	public PpnCtlword() {
		super();
	}

	public PpnCtlword(String cwId) {
		this.cwId = cwId;
	}

	/**
	 * @return the cwCreatetime
	 */
	public Timestamp getCwCreatetime() {
		return this.cwCreatetime;
	}
	
	/**
	 * @param cwCreatetime the cwCreatetime to set
	 */
	public void setCwCreatetime(Timestamp value) {
		this.cwCreatetime = value;
	}

	/**
	 * @return the cwData
	 */
	public String getCwData() {
		return this.cwData;
	}
	
	/**
	 * @param cwData the cwData to set
	 */
	public void setCwData(String value) {
		this.cwData = value;
	}

	/**
	 * @return the cwDesc
	 */
	public String getCwDesc() {
		return this.cwDesc;
	}
	
	/**
	 * @param cwDesc the cwDesc to set
	 */
	public void setCwDesc(String value) {
		this.cwDesc = value;
	}

	/**
	 * @return the cwFieldalias
	 */
	public String getCwFieldalias() {
		return this.cwFieldalias;
	}
	
	/**
	 * @param cwFieldalias the cwFieldalias to set
	 */
	public void setCwFieldalias(String value) {
		this.cwFieldalias = value;
	}

	/**
	 * @return the cwFieldname
	 */
	public String getCwFieldname() {
		return this.cwFieldname;
	}
	
	/**
	 * @param cwFieldname the cwFieldname to set
	 */
	public void setCwFieldname(String value) {
		this.cwFieldname = value;
	}

	/**
	 * @return the cwId
	 */
	public String getCwId() {
		return this.cwId;
	}
	
	/**
	 * @param cwId the cwId to set
	 */
	public void setCwId(String value) {
		this.cwId = value;
	}

	/**
	 * @return the cwName
	 */
	public String getCwName() {
		return this.cwName;
	}
	
	/**
	 * @param cwName the cwName to set
	 */
	public void setCwName(String value) {
		this.cwName = value;
	}

	/**
	 * @return the cwParentid
	 */
	public String getCwParentid() {
		return this.cwParentid;
	}
	
	/**
	 * @param cwParentid the cwParentid to set
	 */
	public void setCwParentid(String value) {
		this.cwParentid = value;
	}

	/**
	 * @return the cwStatus
	 */
	public Integer getCwStatus() {
		return this.cwStatus;
	}
	
	/**
	 * @param cwStatus the cwStatus to set
	 */
	public void setCwStatus(Integer value) {
		this.cwStatus = value;
	}

	/**
	 * @return the cwTablealias
	 */
	public String getCwTablealias() {
		return this.cwTablealias;
	}
	
	/**
	 * @param cwTablealias the cwTablealias to set
	 */
	public void setCwTablealias(String value) {
		this.cwTablealias = value;
	}

	/**
	 * @return the cwTablename
	 */
	public String getCwTablename() {
		return this.cwTablename;
	}
	
	/**
	 * @param cwTablename the cwTablename to set
	 */
	public void setCwTablename(String value) {
		this.cwTablename = value;
	}

	/**
	 * @return the cwType
	 */
	public Integer getCwType() {
		return this.cwType;
	}
	
	/**
	 * @param cwType the cwType to set
	 */
	public void setCwType(Integer value) {
		this.cwType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnCtlword)) {
			return false;
		}
		PpnCtlword other = (PpnCtlword)o;
		if (null == this.cwId) {
			if (other.cwId != null)
				return false;
		} else if (!this.cwId.equals(other.cwId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cwId == null) ? 0 : cwId.hashCode());
		return result;
	}
	
}