/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnCdmChannel.java
 * 日 期：Thu Aug 04 14:46:50 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_CDM_CHANNEL", keyGenerator = "uuid")
public class PpnCdmChannel implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CHAN_ATTACH = "CHAN_ATTACH";
	public static String PROP_CHAN_BEGIN_DATE = "CHAN_BEGIN_DATE";
	public static String PROP_CHAN_CODE = "CHAN_CODE";
	public static String PROP_CHAN_COVER_ZONE = "CHAN_COVER_ZONE";
	public static String PROP_CHAN_DESC = "CHAN_DESC";
	public static String PROP_CHAN_END_DATE = "CHAN_END_DATE";
	public static String PROP_CHAN_FIELD1 = "CHAN_FIELD1";
	public static String PROP_CHAN_FIELD2 = "CHAN_FIELD2";
	public static String PROP_CHAN_HD_FLAG = "CHAN_HD_FLAG";
	public static String PROP_CHAN_ID = "CHAN_ID";
	public static String PROP_CHAN_NAME = "CHAN_NAME";
	public static String PROP_CHAN_PLAY_BEGIN_TIME = "CHAN_PLAY_BEGIN_TIME";
	public static String PROP_CHAN_PLAY_END_TIME = "CHAN_PLAY_END_TIME";
	public static String PROP_CHAN_PLAY_LANG = "CHAN_PLAY_LANG";
	public static String PROP_CHAN_PLAY_SITE = "CHAN_PLAY_SITE";
	public static String PROP_CHAN_STATUS = "CHAN_STATUS";
	public static String PROP_CHAN_TYPE = "CHAN_TYPE";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_TYPE = "CREATE_TYPE";
	public static String PROP_CREATE_USER = "CREATE_USER";
	
	/** primary key field of chanId */
	@FieldMapping(columnName = "CHAN_ID", columnType = 12, primary = true)
	private String chanId;
	@FieldMapping(columnName = "CHAN_ATTACH", columnType = 12)
	private String chanAttach;
	@FieldMapping(columnName = "CHAN_BEGIN_DATE", columnType = 93)
	private Date chanBeginDate;
	@FieldMapping(columnName = "CHAN_CODE", columnType = 12)
	private String chanCode;
	@FieldMapping(columnName = "CHAN_COVER_ZONE", columnType = 12)
	private String chanCoverZone;
	@FieldMapping(columnName = "CHAN_DESC", columnType = 12)
	private String chanDesc;
	@FieldMapping(columnName = "CHAN_END_DATE", columnType = 93)
	private Date chanEndDate;
	@FieldMapping(columnName = "CHAN_FIELD1", columnType = 12)
	private String chanField1;
	@FieldMapping(columnName = "CHAN_FIELD2", columnType = 12)
	private String chanField2;
	@FieldMapping(columnName = "CHAN_HD_FLAG", columnType = 12)
	private String chanHdFlag;
	@FieldMapping(columnName = "CHAN_NAME", columnType = 12)
	private String chanName;
	@FieldMapping(columnName = "CHAN_PLAY_BEGIN_TIME", columnType = 12)
	private String chanPlayBeginTime;
	@FieldMapping(columnName = "CHAN_PLAY_END_TIME", columnType = 12)
	private String chanPlayEndTime;
	@FieldMapping(columnName = "CHAN_PLAY_LANG", columnType = 12)
	private String chanPlayLang;
	@FieldMapping(columnName = "CHAN_PLAY_SITE", columnType = 2)
	private Integer chanPlaySite;
	@FieldMapping(columnName = "CHAN_STATUS", columnType = 2)
	private Integer chanStatus;
	@FieldMapping(columnName = "CHAN_TYPE", columnType = 2)
	private Integer chanType;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_TYPE", columnType = 2)
	private Integer createType;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	
	public PpnCdmChannel() {
		super();
	}

	public PpnCdmChannel(String chanId) {
		this.chanId = chanId;
	}

	public PpnCdmChannel(String chanAttach, Date chanBeginDate, String chanCode, String chanCoverZone, String chanDesc, Date chanEndDate, String chanHdFlag, String chanName, String chanPlayBeginTime, String chanPlayEndTime, String chanPlayLang, Integer chanPlaySite, Integer chanStatus, Integer chanType) {
		this.chanAttach = chanAttach;
		this.chanBeginDate = chanBeginDate;
		this.chanCode = chanCode;
		this.chanCoverZone = chanCoverZone;
		this.chanDesc = chanDesc;
		this.chanEndDate = chanEndDate;
		this.chanHdFlag = chanHdFlag;
		this.chanName = chanName;
		this.chanPlayBeginTime = chanPlayBeginTime;
		this.chanPlayEndTime = chanPlayEndTime;
		this.chanPlayLang = chanPlayLang;
		this.chanPlaySite = chanPlaySite;
		this.chanStatus = chanStatus;
		this.chanType = chanType;
	}

	/**
	 * @return the chanAttach
	 */
	public String getChanAttach() {
		return this.chanAttach;
	}
	
	/**
	 * @param chanAttach the chanAttach to set
	 */
	public void setChanAttach(String value) {
		this.chanAttach = value;
	}

	/**
	 * @return the chanBeginDate
	 */
	public Date getChanBeginDate() {
		return this.chanBeginDate;
	}
	
	/**
	 * @param chanBeginDate the chanBeginDate to set
	 */
	public void setChanBeginDate(Date value) {
		this.chanBeginDate = value;
	}

	/**
	 * @return the chanCode
	 */
	public String getChanCode() {
		return this.chanCode;
	}
	
	/**
	 * @param chanCode the chanCode to set
	 */
	public void setChanCode(String value) {
		this.chanCode = value;
	}

	/**
	 * @return the chanCoverZone
	 */
	public String getChanCoverZone() {
		return this.chanCoverZone;
	}
	
	/**
	 * @param chanCoverZone the chanCoverZone to set
	 */
	public void setChanCoverZone(String value) {
		this.chanCoverZone = value;
	}

	/**
	 * @return the chanDesc
	 */
	public String getChanDesc() {
		return this.chanDesc;
	}
	
	/**
	 * @param chanDesc the chanDesc to set
	 */
	public void setChanDesc(String value) {
		this.chanDesc = value;
	}

	/**
	 * @return the chanEndDate
	 */
	public Date getChanEndDate() {
		return this.chanEndDate;
	}
	
	/**
	 * @param chanEndDate the chanEndDate to set
	 */
	public void setChanEndDate(Date value) {
		this.chanEndDate = value;
	}

	/**
	 * @return the chanField1
	 */
	public String getChanField1() {
		return this.chanField1;
	}
	
	/**
	 * @param chanField1 the chanField1 to set
	 */
	public void setChanField1(String value) {
		this.chanField1 = value;
	}

	/**
	 * @return the chanField2
	 */
	public String getChanField2() {
		return this.chanField2;
	}
	
	/**
	 * @param chanField2 the chanField2 to set
	 */
	public void setChanField2(String value) {
		this.chanField2 = value;
	}

	/**
	 * @return the chanHdFlag
	 */
	public String getChanHdFlag() {
		return this.chanHdFlag;
	}
	
	/**
	 * @param chanHdFlag the chanHdFlag to set
	 */
	public void setChanHdFlag(String value) {
		this.chanHdFlag = value;
	}

	/**
	 * @return the chanId
	 */
	public String getChanId() {
		return this.chanId;
	}
	
	/**
	 * @param chanId the chanId to set
	 */
	public void setChanId(String value) {
		this.chanId = value;
	}

	/**
	 * @return the chanName
	 */
	public String getChanName() {
		return this.chanName;
	}
	
	/**
	 * @param chanName the chanName to set
	 */
	public void setChanName(String value) {
		this.chanName = value;
	}

	/**
	 * @return the chanPlayBeginTime
	 */
	public String getChanPlayBeginTime() {
		return this.chanPlayBeginTime;
	}
	
	/**
	 * @param chanPlayBeginTime the chanPlayBeginTime to set
	 */
	public void setChanPlayBeginTime(String value) {
		this.chanPlayBeginTime = value;
	}

	/**
	 * @return the chanPlayEndTime
	 */
	public String getChanPlayEndTime() {
		return this.chanPlayEndTime;
	}
	
	/**
	 * @param chanPlayEndTime the chanPlayEndTime to set
	 */
	public void setChanPlayEndTime(String value) {
		this.chanPlayEndTime = value;
	}

	/**
	 * @return the chanPlayLang
	 */
	public String getChanPlayLang() {
		return this.chanPlayLang;
	}
	
	/**
	 * @param chanPlayLang the chanPlayLang to set
	 */
	public void setChanPlayLang(String value) {
		this.chanPlayLang = value;
	}

	/**
	 * @return the chanPlaySite
	 */
	public Integer getChanPlaySite() {
		return this.chanPlaySite;
	}
	
	/**
	 * @param chanPlaySite the chanPlaySite to set
	 */
	public void setChanPlaySite(Integer value) {
		this.chanPlaySite = value;
	}

	/**
	 * @return the chanStatus
	 */
	public Integer getChanStatus() {
		return this.chanStatus;
	}
	
	/**
	 * @param chanStatus the chanStatus to set
	 */
	public void setChanStatus(Integer value) {
		this.chanStatus = value;
	}

	/**
	 * @return the chanType
	 */
	public Integer getChanType() {
		return this.chanType;
	}
	
	/**
	 * @param chanType the chanType to set
	 */
	public void setChanType(Integer value) {
		this.chanType = value;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date value) {
		this.createTime = value;
	}

	/**
	 * @return the createType
	 */
	public Integer getCreateType() {
		return this.createType;
	}
	
	/**
	 * @param createType the createType to set
	 */
	public void setCreateType(Integer value) {
		this.createType = value;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String value) {
		this.createUser = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnCdmChannel)) {
			return false;
		}
		PpnCdmChannel other = (PpnCdmChannel)o;
		if (null == this.chanId) {
			if (other.chanId != null)
				return false;
		} else if (!this.chanId.equals(other.chanId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chanId == null) ? 0 : chanId.hashCode());
		return result;
	}
	
}