/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnDevOperateLog.java
 * 日 期：Mon Sep 12 14:02:52 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_DEV_OPERATE_LOG", keyGenerator = "uuid")
public class PpnDevOperateLog implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_DEV_ID = "DEV_ID";
	public static String PROP_LOG_DESC = "LOG_DESC";
	public static String PROP_LOG_FIELD1 = "LOG_FIELD1";
	public static String PROP_LOG_FIELD2 = "LOG_FIELD2";
	public static String PROP_LOG_ID = "LOG_ID";
	public static String PROP_LOG_TIME = "LOG_TIME";
	public static String PROP_LOG_TYPE = "LOG_TYPE";
	public static String PROP_LOG_USER = "LOG_USER";
	
	/** primary key field of logId */
	@FieldMapping(columnName = "LOG_ID", columnType = 12, primary = true)
	private String logId;
	/** foreign key field of PPN_DEV_DEVICE.DEV_ID */
	@FieldMapping(columnName = "DEV_ID", columnType = 12)
	private String devId;
	@FieldMapping(columnName = "LOG_DESC", columnType = 12)
	private String logDesc;
	@FieldMapping(columnName = "LOG_FIELD1", columnType = 12)
	private String logField1;
	@FieldMapping(columnName = "LOG_FIELD2", columnType = 12)
	private String logField2;
	@FieldMapping(columnName = "LOG_TIME", columnType = 93)
	private Date logTime;
	@FieldMapping(columnName = "LOG_TYPE", columnType = 12)
	private String logType;
	@FieldMapping(columnName = "LOG_USER", columnType = 12)
	private String logUser;
	
	public PpnDevOperateLog() {
		super();
	}

	public PpnDevOperateLog(String logId) {
		this.logId = logId;
	}

	/**
	 * @return the devId
	 */
	public String getDevId() {
		return this.devId;
	}
	
	/**
	 * @param devId the devId to set
	 */
	public void setDevId(String value) {
		this.devId = value;
	}

	/**
	 * @return the logDesc
	 */
	public String getLogDesc() {
		return this.logDesc;
	}
	
	/**
	 * @param logDesc the logDesc to set
	 */
	public void setLogDesc(String value) {
		this.logDesc = value;
	}

	/**
	 * @return the logField1
	 */
	public String getLogField1() {
		return this.logField1;
	}
	
	/**
	 * @param logField1 the logField1 to set
	 */
	public void setLogField1(String value) {
		this.logField1 = value;
	}

	/**
	 * @return the logField2
	 */
	public String getLogField2() {
		return this.logField2;
	}
	
	/**
	 * @param logField2 the logField2 to set
	 */
	public void setLogField2(String value) {
		this.logField2 = value;
	}

	/**
	 * @return the logId
	 */
	public String getLogId() {
		return this.logId;
	}
	
	/**
	 * @param logId the logId to set
	 */
	public void setLogId(String value) {
		this.logId = value;
	}

	/**
	 * @return the logTime
	 */
	public Date getLogTime() {
		return this.logTime;
	}
	
	/**
	 * @param logTime the logTime to set
	 */
	public void setLogTime(Date value) {
		this.logTime = value;
	}

	/**
	 * @return the logType
	 */
	public String getLogType() {
		return this.logType;
	}
	
	/**
	 * @param logType the logType to set
	 */
	public void setLogType(String value) {
		this.logType = value;
	}

	/**
	 * @return the logUser
	 */
	public String getLogUser() {
		return this.logUser;
	}
	
	/**
	 * @param logUser the logUser to set
	 */
	public void setLogUser(String value) {
		this.logUser = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnDevOperateLog)) {
			return false;
		}
		PpnDevOperateLog other = (PpnDevOperateLog)o;
		if (null == this.logId) {
			if (other.logId != null)
				return false;
		} else if (!this.logId.equals(other.logId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((logId == null) ? 0 : logId.hashCode());
		return result;
	}
	
}