/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnPgmBpoint.java
 * 日 期：Sat Jul 30 15:02:49 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_PGM_BPOINT", keyGenerator = "uuid")
public class PpnPgmBpoint implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_BPOINT_CODE = "BPOINT_CODE";
	public static String PROP_BPOINT_CREATE_TIME = "BPOINT_CREATE_TIME";
	public static String PROP_BPOINT_DESC = "BPOINT_DESC";
	public static String PROP_BPOINT_FIELD1 = "BPOINT_FIELD1";
	public static String PROP_BPOINT_ID = "BPOINT_ID";
	public static String PROP_BPOINT_POSITION = "BPOINT_POSITION";
	public static String PROP_PGM_ID = "PGM_ID";
	
	/** primary key field of bpointId */
	@FieldMapping(columnName = "BPOINT_ID", columnType = 12, primary = true)
	private String bpointId;
	@FieldMapping(columnName = "BPOINT_CODE", columnType = 12)
	private String bpointCode;
	@FieldMapping(columnName = "BPOINT_CREATE_TIME", columnType = 93)
	private Date bpointCreateTime;
	@FieldMapping(columnName = "BPOINT_DESC", columnType = 12)
	private String bpointDesc;
	@FieldMapping(columnName = "BPOINT_FIELD1", columnType = 12)
	private String bpointField1;
	@FieldMapping(columnName = "BPOINT_POSITION", columnType = 12)
	private String bpointPosition;
	@FieldMapping(columnName = "PGM_ID", columnType = 12)
	private String pgmId;
	
	public PpnPgmBpoint() {
		super();
	}

	public PpnPgmBpoint(String bpointId) {
		this.bpointId = bpointId;
	}

	/**
	 * @return the bpointCode
	 */
	public String getBpointCode() {
		return this.bpointCode;
	}
	
	/**
	 * @param bpointCode the bpointCode to set
	 */
	public void setBpointCode(String value) {
		this.bpointCode = value;
	}

	/**
	 * @return the bpointCreateTime
	 */
	public Date getBpointCreateTime() {
		return this.bpointCreateTime;
	}
	
	/**
	 * @param bpointCreateTime the bpointCreateTime to set
	 */
	public void setBpointCreateTime(Date value) {
		this.bpointCreateTime = value;
	}

	/**
	 * @return the bpointDesc
	 */
	public String getBpointDesc() {
		return this.bpointDesc;
	}
	
	/**
	 * @param bpointDesc the bpointDesc to set
	 */
	public void setBpointDesc(String value) {
		this.bpointDesc = value;
	}

	/**
	 * @return the bpointField1
	 */
	public String getBpointField1() {
		return this.bpointField1;
	}
	
	/**
	 * @param bpointField1 the bpointField1 to set
	 */
	public void setBpointField1(String value) {
		this.bpointField1 = value;
	}

	/**
	 * @return the bpointId
	 */
	public String getBpointId() {
		return this.bpointId;
	}
	
	/**
	 * @param bpointId the bpointId to set
	 */
	public void setBpointId(String value) {
		this.bpointId = value;
	}

	/**
	 * @return the bpointPosition
	 */
	public String getBpointPosition() {
		return this.bpointPosition;
	}
	
	/**
	 * @param bpointPosition the bpointPosition to set
	 */
	public void setBpointPosition(String value) {
		this.bpointPosition = value;
	}

	/**
	 * @return the pgmId
	 */
	public String getPgmId() {
		return this.pgmId;
	}
	
	/**
	 * @param pgmId the pgmId to set
	 */
	public void setPgmId(String value) {
		this.pgmId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnPgmBpoint)) {
			return false;
		}
		PpnPgmBpoint other = (PpnPgmBpoint)o;
		if (null == this.bpointId) {
			if (other.bpointId != null)
				return false;
		} else if (!this.bpointId.equals(other.bpointId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bpointId == null) ? 0 : bpointId.hashCode());
		return result;
	}
	
}