/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnQcTaskfile.java
 * 日 期：Fri Apr 10 11:31:24 CST 2015
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_QC_TASKFILE", keyGenerator = "uuid")
public class PpnQcTaskfile implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_FILE_CODE = "FILE_CODE";
	public static String PROP_FILE_FIELD1 = "FILE_FIELD1";
	public static String PROP_FILE_FIELD2 = "FILE_FIELD2";
	public static String PROP_FILE_ID = "FILE_ID";
	public static String PROP_FILE_NAME = "FILE_NAME";
	public static String PROP_FILE_PATH = "FILE_PATH";
	public static String PROP_FILE_QCSTATUS = "FILE_QCSTATUS";
	public static String PROP_FILE_TYPE = "FILE_TYPE";
	public static String PROP_TASK_ID = "TASK_ID";
	
	/** primary key field of fileId */
	@FieldMapping(columnName = "FILE_ID", columnType = 12, primary = true)
	private String fileId;
	@FieldMapping(columnName = "FILE_CODE", columnType = 12)
	private String fileCode;
	@FieldMapping(columnName = "FILE_FIELD1", columnType = 12)
	private String fileField1;
	@FieldMapping(columnName = "FILE_FIELD2", columnType = 12)
	private String fileField2;
	@FieldMapping(columnName = "FILE_NAME", columnType = 12)
	private String fileName;
	@FieldMapping(columnName = "FILE_PATH", columnType = 12)
	private String filePath;
	@FieldMapping(columnName = "FILE_QCSTATUS", columnType = 2)
	private Integer fileQcstatus;
	@FieldMapping(columnName = "FILE_TYPE", columnType = 2)
	private Integer fileType;
	@FieldMapping(columnName = "TASK_ID", columnType = 12)
	private String taskId;
	
	public PpnQcTaskfile() {
		super();
	}

	public PpnQcTaskfile(String fileId) {
		this.fileId = fileId;
	}

	public PpnQcTaskfile(String fileName, String filePath, Integer fileQcstatus, Integer fileType, String taskId) {
		this.fileName = fileName;
		this.filePath = filePath;
		this.fileQcstatus = fileQcstatus;
		this.fileType = fileType;
		this.taskId = taskId;
	}

	/**
	 * @return the fileCode
	 */
	public String getFileCode() {
		return this.fileCode;
	}
	
	/**
	 * @param fileCode the fileCode to set
	 */
	public void setFileCode(String value) {
		this.fileCode = value;
	}

	/**
	 * @return the fileField1
	 */
	public String getFileField1() {
		return this.fileField1;
	}
	
	/**
	 * @param fileField1 the fileField1 to set
	 */
	public void setFileField1(String value) {
		this.fileField1 = value;
	}

	/**
	 * @return the fileField2
	 */
	public String getFileField2() {
		return this.fileField2;
	}
	
	/**
	 * @param fileField2 the fileField2 to set
	 */
	public void setFileField2(String value) {
		this.fileField2 = value;
	}

	/**
	 * @return the fileId
	 */
	public String getFileId() {
		return this.fileId;
	}
	
	/**
	 * @param fileId the fileId to set
	 */
	public void setFileId(String value) {
		this.fileId = value;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return this.fileName;
	}
	
	/**
	 * @param fileName the fileName to set
	 */
	public void setFileName(String value) {
		this.fileName = value;
	}

	/**
	 * @return the filePath
	 */
	public String getFilePath() {
		return this.filePath;
	}
	
	/**
	 * @param filePath the filePath to set
	 */
	public void setFilePath(String value) {
		this.filePath = value;
	}

	/**
	 * @return the fileQcstatus
	 */
	public Integer getFileQcstatus() {
		return this.fileQcstatus;
	}
	
	/**
	 * @param fileQcstatus the fileQcstatus to set
	 */
	public void setFileQcstatus(Integer value) {
		this.fileQcstatus = value;
	}

	/**
	 * @return the fileType
	 */
	public Integer getFileType() {
		return this.fileType;
	}
	
	/**
	 * @param fileType the fileType to set
	 */
	public void setFileType(Integer value) {
		this.fileType = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnQcTaskfile)) {
			return false;
		}
		PpnQcTaskfile other = (PpnQcTaskfile)o;
		if (null == this.fileId) {
			if (other.fileId != null)
				return false;
		} else if (!this.fileId.equals(other.fileId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fileId == null) ? 0 : fileId.hashCode());
		return result;
	}
	
}