/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnQcTask.java
 * 日 期：Fri Apr 10 11:31:23 CST 2015
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_QC_TASK", keyGenerator = "uuid")
public class PpnQcTask implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_TASK_CREATETIME = "TASK_CREATETIME";
	public static String PROP_TASK_CREATEUSERID = "TASK_CREATEUSERID";
	public static String PROP_TASK_DESC = "TASK_DESC";
	public static String PROP_TASK_EXECTYPE = "TASK_EXECTYPE";
	public static String PROP_TASK_FIELD1 = "TASK_FIELD1";
	public static String PROP_TASK_FIELD2 = "TASK_FIELD2";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_MODE = "TASK_MODE";
	public static String PROP_TASK_NAME = "TASK_NAME";
	public static String PROP_TASK_PRIORITY = "TASK_PRIORITY";
	public static String PROP_TASK_RESULTPATH = "TASK_RESULTPATH";
	public static String PROP_TASK_RULEID = "TASK_RULEID";
	public static String PROP_TASK_RULENAME = "TASK_RULENAME";
	public static String PROP_TASK_STATUS = "TASK_STATUS";
	public static String PROP_TASK_TYPE = "TASK_TYPE";
	
	/** primary key field of taskId */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "TASK_CREATETIME", columnType = 93)
	private Timestamp taskCreatetime;
	@FieldMapping(columnName = "TASK_CREATEUSERID", columnType = 12)
	private String taskCreateuserid;
	@FieldMapping(columnName = "TASK_DESC", columnType = 12)
	private String taskDesc;
	@FieldMapping(columnName = "TASK_EXECTYPE", columnType = 2)
	private Integer taskExectype;
	@FieldMapping(columnName = "TASK_FIELD1", columnType = 12)
	private String taskField1;
	@FieldMapping(columnName = "TASK_FIELD2", columnType = 12)
	private String taskField2;
	@FieldMapping(columnName = "TASK_MODE", columnType = 2)
	private Integer taskMode;
	@FieldMapping(columnName = "TASK_NAME", columnType = 12)
	private String taskName;
	@FieldMapping(columnName = "TASK_PRIORITY", columnType = 2)
	private Integer taskPriority;
	@FieldMapping(columnName = "TASK_RESULTPATH", columnType = 12)
	private String taskResultpath;
	@FieldMapping(columnName = "TASK_RULEID", columnType = 12)
	private String taskRuleid;
	@FieldMapping(columnName = "TASK_RULENAME", columnType = 12)
	private String taskRulename;
	@FieldMapping(columnName = "TASK_STATUS", columnType = 2)
	private Integer taskStatus;
	@FieldMapping(columnName = "TASK_TYPE", columnType = 2)
	private Integer taskType;
	
	public PpnQcTask() {
		super();
	}

	public PpnQcTask(String taskId) {
		this.taskId = taskId;
	}

	public PpnQcTask(Timestamp taskCreatetime, Integer taskMode, String taskName, Integer taskStatus, Integer taskType) {
		this.taskCreatetime = taskCreatetime;
		this.taskMode = taskMode;
		this.taskName = taskName;
		this.taskStatus = taskStatus;
		this.taskType = taskType;
	}

	/**
	 * @return the taskCreatetime
	 */
	public Timestamp getTaskCreatetime() {
		return this.taskCreatetime;
	}
	
	/**
	 * @param taskCreatetime the taskCreatetime to set
	 */
	public void setTaskCreatetime(Timestamp value) {
		this.taskCreatetime = value;
	}

	/**
	 * @return the taskCreateuserid
	 */
	public String getTaskCreateuserid() {
		return this.taskCreateuserid;
	}
	
	/**
	 * @param taskCreateuserid the taskCreateuserid to set
	 */
	public void setTaskCreateuserid(String value) {
		this.taskCreateuserid = value;
	}

	/**
	 * @return the taskDesc
	 */
	public String getTaskDesc() {
		return this.taskDesc;
	}
	
	/**
	 * @param taskDesc the taskDesc to set
	 */
	public void setTaskDesc(String value) {
		this.taskDesc = value;
	}

	/**
	 * @return the taskExectype
	 */
	public Integer getTaskExectype() {
		return this.taskExectype;
	}
	
	/**
	 * @param taskExectype the taskExectype to set
	 */
	public void setTaskExectype(Integer value) {
		this.taskExectype = value;
	}

	/**
	 * @return the taskField1
	 */
	public String getTaskField1() {
		return this.taskField1;
	}
	
	/**
	 * @param taskField1 the taskField1 to set
	 */
	public void setTaskField1(String value) {
		this.taskField1 = value;
	}

	/**
	 * @return the taskField2
	 */
	public String getTaskField2() {
		return this.taskField2;
	}
	
	/**
	 * @param taskField2 the taskField2 to set
	 */
	public void setTaskField2(String value) {
		this.taskField2 = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/**
	 * @return the taskMode
	 */
	public Integer getTaskMode() {
		return this.taskMode;
	}
	
	/**
	 * @param taskMode the taskMode to set
	 */
	public void setTaskMode(Integer value) {
		this.taskMode = value;
	}

	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return this.taskName;
	}
	
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String value) {
		this.taskName = value;
	}

	/**
	 * @return the taskPriority
	 */
	public Integer getTaskPriority() {
		return this.taskPriority;
	}
	
	/**
	 * @param taskPriority the taskPriority to set
	 */
	public void setTaskPriority(Integer value) {
		this.taskPriority = value;
	}

	/**
	 * @return the taskResultpath
	 */
	public String getTaskResultpath() {
		return this.taskResultpath;
	}
	
	/**
	 * @param taskResultpath the taskResultpath to set
	 */
	public void setTaskResultpath(String value) {
		this.taskResultpath = value;
	}

	/**
	 * @return the taskRuleid
	 */
	public String getTaskRuleid() {
		return this.taskRuleid;
	}
	
	/**
	 * @param taskRuleid the taskRuleid to set
	 */
	public void setTaskRuleid(String value) {
		this.taskRuleid = value;
	}

	/**
	 * @return the taskRulename
	 */
	public String getTaskRulename() {
		return this.taskRulename;
	}
	
	/**
	 * @param taskRulename the taskRulename to set
	 */
	public void setTaskRulename(String value) {
		this.taskRulename = value;
	}

	/**
	 * @return the taskStatus
	 */
	public Integer getTaskStatus() {
		return this.taskStatus;
	}
	
	/**
	 * @param taskStatus the taskStatus to set
	 */
	public void setTaskStatus(Integer value) {
		this.taskStatus = value;
	}

	/**
	 * @return the taskType
	 */
	public Integer getTaskType() {
		return this.taskType;
	}
	
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(Integer value) {
		this.taskType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnQcTask)) {
			return false;
		}
		PpnQcTask other = (PpnQcTask)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}