/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.trm.bean.PpnStorUsergroup.java
 * 日 期：Mon Aug 01 23:08:49 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_STOR_USERGROUP", keyGenerator = "uuid")
public class PpnStorUsergroup implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_GROUP_CREATE_TIME = "GROUP_CREATE_TIME";
	public static String PROP_GROUP_CREATE_USER = "GROUP_CREATE_USER";
	public static String PROP_GROUP_FIELD1 = "GROUP_FIELD1";
	public static String PROP_GROUP_ID = "GROUP_ID";
	public static String PROP_GROUP_NAME = "GROUP_NAME";
	public static String PROP_GROUP_SCOPE = "GROUP_SCOPE";
	public static String PROP_GROUP_TYPE = "GROUP_TYPE";
	
	/** primary key field of groupId */
	@FieldMapping(columnName = "GROUP_ID", columnType = 12, primary = true)
	private String groupId;
	@FieldMapping(columnName = "GROUP_CREATE_TIME", columnType = 93)
	private Date groupCreateTime;
	@FieldMapping(columnName = "GROUP_CREATE_USER", columnType = 12)
	private String groupCreateUser;
	@FieldMapping(columnName = "GROUP_FIELD1", columnType = 12)
	private String groupField1;
	@FieldMapping(columnName = "GROUP_NAME", columnType = 12)
	private String groupName;
	@FieldMapping(columnName = "GROUP_SCOPE", columnType = 12)
	private String groupScope;
	@FieldMapping(columnName = "GROUP_TYPE", columnType = 2)
	private Integer groupType;
	
	public PpnStorUsergroup() {
		super();
	}

	public PpnStorUsergroup(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * @return the groupCreateTime
	 */
	public Date getGroupCreateTime() {
		return this.groupCreateTime;
	}
	
	/**
	 * @param groupCreateTime the groupCreateTime to set
	 */
	public void setGroupCreateTime(Date value) {
		this.groupCreateTime = value;
	}

	/**
	 * @return the groupCreateUser
	 */
	public String getGroupCreateUser() {
		return this.groupCreateUser;
	}
	
	/**
	 * @param groupCreateUser the groupCreateUser to set
	 */
	public void setGroupCreateUser(String value) {
		this.groupCreateUser = value;
	}

	/**
	 * @return the groupField1
	 */
	public String getGroupField1() {
		return this.groupField1;
	}
	
	/**
	 * @param groupField1 the groupField1 to set
	 */
	public void setGroupField1(String value) {
		this.groupField1 = value;
	}

	/**
	 * @return the groupId
	 */
	public String getGroupId() {
		return this.groupId;
	}
	
	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(String value) {
		this.groupId = value;
	}

	/**
	 * @return the groupName
	 */
	public String getGroupName() {
		return this.groupName;
	}
	
	/**
	 * @param groupName the groupName to set
	 */
	public void setGroupName(String value) {
		this.groupName = value;
	}

	/**
	 * @return the groupScope
	 */
	public String getGroupScope() {
		return this.groupScope;
	}
	
	/**
	 * @param groupScope the groupScope to set
	 */
	public void setGroupScope(String value) {
		this.groupScope = value;
	}

	/**
	 * @return the groupType
	 */
	public Integer getGroupType() {
		return this.groupType;
	}
	
	/**
	 * @param groupType the groupType to set
	 */
	public void setGroupType(Integer value) {
		this.groupType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnStorUsergroup)) {
			return false;
		}
		PpnStorUsergroup other = (PpnStorUsergroup)o;
		if (null == this.groupId) {
			if (other.groupId != null)
				return false;
		} else if (!this.groupId.equals(other.groupId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((groupId == null) ? 0 : groupId.hashCode());
		return result;
	}
	
}