/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.trm.bean.PpnStorDirTemplate.java
 * 日 期：Tue Aug 02 00:06:25 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_STOR_DIR_TEMPLATE", keyGenerator = "uuid")
public class PpnStorDirTemplate implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_TMPL_CREATE_TIME = "TMPL_CREATE_TIME";
	public static String PROP_TMPL_CREATE_USER = "TMPL_CREATE_USER";
	public static String PROP_TMPL_DATA = "TMPL_DATA";
	public static String PROP_TMPL_DESC = "TMPL_DESC";
	public static String PROP_TMPL_FIELD1 = "TMPL_FIELD1";
	public static String PROP_TMPL_ID = "TMPL_ID";
	public static String PROP_TMPL_NAME = "TMPL_NAME";
	public static String PROP_TMPL_STATUS = "TMPL_STATUS";
	
	/** primary key field of tmplId */
	@FieldMapping(columnName = "TMPL_ID", columnType = 12, primary = true)
	private String tmplId;
	@FieldMapping(columnName = "TMPL_CREATE_TIME", columnType = 93)
	private Date tmplCreateTime;
	@FieldMapping(columnName = "TMPL_CREATE_USER", columnType = 12)
	private String tmplCreateUser;
	@FieldMapping(columnName = "TMPL_DATA", columnType = 12)
	private String tmplData;
	@FieldMapping(columnName = "TMPL_DESC", columnType = 12)
	private String tmplDesc;
	@FieldMapping(columnName = "TMPL_FIELD1", columnType = 12)
	private String tmplField1;
	@FieldMapping(columnName = "TMPL_NAME", columnType = 12)
	private String tmplName;
	@FieldMapping(columnName = "TMPL_STATUS", columnType = 2)
	private Integer tmplStatus;
	
	public PpnStorDirTemplate() {
		super();
	}

	public PpnStorDirTemplate(String tmplId) {
		this.tmplId = tmplId;
	}

	/**
	 * @return the tmplCreateTime
	 */
	public Date getTmplCreateTime() {
		return this.tmplCreateTime;
	}
	
	/**
	 * @param tmplCreateTime the tmplCreateTime to set
	 */
	public void setTmplCreateTime(Date value) {
		this.tmplCreateTime = value;
	}

	/**
	 * @return the tmplCreateUser
	 */
	public String getTmplCreateUser() {
		return this.tmplCreateUser;
	}
	
	/**
	 * @param tmplCreateUser the tmplCreateUser to set
	 */
	public void setTmplCreateUser(String value) {
		this.tmplCreateUser = value;
	}

	/**
	 * @return the tmplData
	 */
	public String getTmplData() {
		return this.tmplData;
	}
	
	/**
	 * @param tmplData the tmplData to set
	 */
	public void setTmplData(String value) {
		this.tmplData = value;
	}

	/**
	 * @return the tmplDesc
	 */
	public String getTmplDesc() {
		return this.tmplDesc;
	}
	
	/**
	 * @param tmplDesc the tmplDesc to set
	 */
	public void setTmplDesc(String value) {
		this.tmplDesc = value;
	}

	/**
	 * @return the tmplField1
	 */
	public String getTmplField1() {
		return this.tmplField1;
	}
	
	/**
	 * @param tmplField1 the tmplField1 to set
	 */
	public void setTmplField1(String value) {
		this.tmplField1 = value;
	}

	/**
	 * @return the tmplId
	 */
	public String getTmplId() {
		return this.tmplId;
	}
	
	/**
	 * @param tmplId the tmplId to set
	 */
	public void setTmplId(String value) {
		this.tmplId = value;
	}

	/**
	 * @return the tmplName
	 */
	public String getTmplName() {
		return this.tmplName;
	}
	
	/**
	 * @param tmplName the tmplName to set
	 */
	public void setTmplName(String value) {
		this.tmplName = value;
	}

	/**
	 * @return the tmplStatus
	 */
	public Integer getTmplStatus() {
		return this.tmplStatus;
	}
	
	/**
	 * @param tmplStatus the tmplStatus to set
	 */
	public void setTmplStatus(Integer value) {
		this.tmplStatus = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnStorDirTemplate)) {
			return false;
		}
		PpnStorDirTemplate other = (PpnStorDirTemplate)o;
		if (null == this.tmplId) {
			if (other.tmplId != null)
				return false;
		} else if (!this.tmplId.equals(other.tmplId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((tmplId == null) ? 0 : tmplId.hashCode());
		return result;
	}
	
}