/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnStorGroupMember.java
 * 日 期：Thu Aug 04 14:46:54 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_STOR_GROUP_MEMBER", keyGenerator = "uuid")
public class PpnStorGroupMember implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_GROUP_ID = "GROUP_ID";
	public static String PROP_MEM_ID = "MEM_ID";
	public static String PROP_USER_ID = "USER_ID";
	
	/** primary key field of memId */
	@FieldMapping(columnName = "MEM_ID", columnType = 12, primary = true)
	private String memId;
	/** foreign key field of PPN_STOR_USERGROUP.GROUP_ID */
	@FieldMapping(columnName = "GROUP_ID", columnType = 12)
	private String groupId;
	/** foreign key field of PPN_STOR_USER.USER_ID */
	@FieldMapping(columnName = "USER_ID", columnType = 12)
	private String userId;
	
	public PpnStorGroupMember() {
		super();
	}

	public PpnStorGroupMember(String memId) {
		this.memId = memId;
	}

	/**
	 * @return the groupId
	 */
	public String getGroupId() {
		return this.groupId;
	}
	
	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(String value) {
		this.groupId = value;
	}

	/**
	 * @return the memId
	 */
	public String getMemId() {
		return this.memId;
	}
	
	/**
	 * @param memId the memId to set
	 */
	public void setMemId(String value) {
		this.memId = value;
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return this.userId;
	}
	
	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String value) {
		this.userId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnStorGroupMember)) {
			return false;
		}
		PpnStorGroupMember other = (PpnStorGroupMember)o;
		if (null == this.memId) {
			if (other.memId != null)
				return false;
		} else if (!this.memId.equals(other.memId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((memId == null) ? 0 : memId.hashCode());
		return result;
	}
	
}