/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnTranstask.java
 * 日 期：Wed Oct 28 10:48:14 CST 2015
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TRANSTASK", keyGenerator = "uuid")
public class PpnTranstask implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AFD_VALUE = "AFD_VALUE";
	public static String PROP_AUDIO_LANG = "AUDIO_LANG";
	public static String PROP_AUDIO_TYPE = "AUDIO_TYPE";
	public static String PROP_AUDIT_TASKCODE = "AUDIT_TASKCODE";
	public static String PROP_AUDIT_TYPE = "AUDIT_TYPE";
	public static String PROP_CLIP_TYPE = "CLIP_TYPE";
	public static String PROP_COLUMN_CODE = "COLUMN_CODE";
	public static String PROP_COLUMN_NAME = "COLUMN_NAME";
	public static String PROP_EMB_TASKCODE = "EMB_TASKCODE";
	public static String PROP_EXCH_TASKCODE = "EXCH_TASKCODE";
	public static String PROP_EXT_PARAM = "EXT_PARAM";
	public static String PROP_FLOW_NUMBER = "FLOW_NUMBER";
	public static String PROP_MATERIAL_CODE = "MATERIAL_CODE";
	public static String PROP_MATERIAL_NAME = "MATERIAL_NAME";
	public static String PROP_MATERIAL_SUM = "MATERIAL_SUM";
	public static String PROP_MATERIAL_TYPE = "MATERIAL_TYPE";
	public static String PROP_PARENT_PROCEXECID = "PARENT_PROCEXECID";
	public static String PROP_PARENT_TRANSTASKID = "PARENT_TRANSTASKID";
	public static String PROP_PGM_CODE = "PGM_CODE";
	public static String PROP_PGM_ID = "PGM_ID";
	public static String PROP_PGM_NAME = "PGM_NAME";
	public static String PROP_PROCEXEC_ID = "PROCEXEC_ID";
	public static String PROP_PRODTASK_CODE = "PRODTASK_CODE";
	public static String PROP_SEGMENT_INDEX = "SEGMENT_INDEX";
	public static String PROP_SRC_GROUPTYPE = "SRC_GROUPTYPE";
	public static String PROP_SRC_SYSCODE = "SRC_SYSCODE";
	public static String PROP_SUBTITLE_LANG = "SUBTITLE_LANG";
	public static String PROP_TARGET_AUDIOCODE = "TARGET_AUDIOCODE";
	public static String PROP_TARGET_AUDIONAME = "TARGET_AUDIONAME";
	public static String PROP_TARGET_PGMCODE = "TARGET_PGMCODE";
	public static String PROP_TARGET_PGMNAME = "TARGET_PGMNAME";
	public static String PROP_TARGET_SUBTITLEAME = "TARGET_SUBTITLEAME";
	public static String PROP_TARGET_SUBTITLECODE = "TARGET_SUBTITLECODE";
	public static String PROP_TARGET_SYSCODE = "TARGET_SYSCODE";
	public static String PROP_TRANS_GROUPTYPE = "TRANS_GROUPTYPE";
	public static String PROP_TRANSTASK_CODE = "TRANSTASK_CODE";
	public static String PROP_TRANSTASK_CREATETIME = "TRANSTASK_CREATETIME";
	public static String PROP_TRANSTASK_DESC = "TRANSTASK_DESC";
	public static String PROP_TRANSTASK_ENDTIME = "TRANSTASK_ENDTIME";
	public static String PROP_TRANSTASK_FIELD1 = "TRANSTASK_FIELD1";
	public static String PROP_TRANSTASK_FIELD2 = "TRANSTASK_FIELD2";
	public static String PROP_TRANSTASK_FIELD3 = "TRANSTASK_FIELD3";
	public static String PROP_TRANSTASK_ID = "TRANSTASK_ID";
	public static String PROP_TRANSTASK_NAME = "TRANSTASK_NAME";
	public static String PROP_TRANSTASK_STARTTIME = "TRANSTASK_STARTTIME";
	public static String PROP_TRANSTASK_STATUS = "TRANSTASK_STATUS";
	public static String PROP_TRANSTASK_STATUSDESC = "TRANSTASK_STATUSDESC";
	public static String PROP_TRANSTASK_TYPE = "TRANSTASK_TYPE";
	
	/** primary key field of transtaskId */
	@FieldMapping(columnName = "TRANSTASK_ID", columnType = 12, primary = true)
	private String transtaskId;
	@FieldMapping(columnName = "AFD_VALUE", columnType = 12)
	private String afdValue;
	@FieldMapping(columnName = "AUDIO_LANG", columnType = 12)
	private String audioLang;
	@FieldMapping(columnName = "AUDIO_TYPE", columnType = 12)
	private String audioType;
	@FieldMapping(columnName = "AUDIT_TASKCODE", columnType = 12)
	private String auditTaskcode;
	@FieldMapping(columnName = "AUDIT_TYPE", columnType = 2)
	private Integer auditType;
	@FieldMapping(columnName = "CLIP_TYPE", columnType = 12)
	private String clipType;
	@FieldMapping(columnName = "COLUMN_CODE", columnType = 12)
	private String columnCode;
	@FieldMapping(columnName = "COLUMN_NAME", columnType = 12)
	private String columnName;
	@FieldMapping(columnName = "EMB_TASKCODE", columnType = 12)
	private String embTaskcode;
	@FieldMapping(columnName = "EXCH_TASKCODE", columnType = 12)
	private String exchTaskcode;
	@FieldMapping(columnName = "EXT_PARAM", columnType = 12)
	private String extParam;
	@FieldMapping(columnName = "FLOW_NUMBER", columnType = 2)
	private Integer flowNumber;
	@FieldMapping(columnName = "MATERIAL_CODE", columnType = 12)
	private String materialCode;
	@FieldMapping(columnName = "MATERIAL_NAME", columnType = 12)
	private String materialName;
	@FieldMapping(columnName = "MATERIAL_SUM", columnType = 2)
	private Integer materialSum;
	@FieldMapping(columnName = "MATERIAL_TYPE", columnType = 12)
	private String materialType;
	@FieldMapping(columnName = "PARENT_PROCEXECID", columnType = 12)
	private String parentProcexecid;
	@FieldMapping(columnName = "PARENT_TRANSTASKID", columnType = 12)
	private String parentTranstaskid;
	@FieldMapping(columnName = "PGM_CODE", columnType = 12)
	private String pgmCode;
	@FieldMapping(columnName = "PGM_ID", columnType = 12)
	private String pgmId;
	@FieldMapping(columnName = "PGM_NAME", columnType = 12)
	private String pgmName;
	@FieldMapping(columnName = "PROCEXEC_ID", columnType = 12)
	private String procexecId;
	@FieldMapping(columnName = "PRODTASK_CODE", columnType = 12)
	private String prodtaskCode;
	@FieldMapping(columnName = "SEGMENT_INDEX", columnType = 2)
	private Integer segmentIndex;
	@FieldMapping(columnName = "SRC_GROUPTYPE", columnType = 12)
	private String srcGrouptype;
	@FieldMapping(columnName = "SRC_SYSCODE", columnType = 12)
	private String srcSyscode;
	@FieldMapping(columnName = "SUBTITLE_LANG", columnType = 12)
	private String subtitleLang;
	@FieldMapping(columnName = "TARGET_AUDIOCODE", columnType = 12)
	private String targetAudiocode;
	@FieldMapping(columnName = "TARGET_AUDIONAME", columnType = 12)
	private String targetAudioname;
	@FieldMapping(columnName = "TARGET_PGMCODE", columnType = 12)
	private String targetPgmcode;
	@FieldMapping(columnName = "TARGET_PGMNAME", columnType = 12)
	private String targetPgmname;
	@FieldMapping(columnName = "TARGET_SUBTITLEAME", columnType = 12)
	private String targetSubtitleame;
	@FieldMapping(columnName = "TARGET_SUBTITLECODE", columnType = 12)
	private String targetSubtitlecode;
	@FieldMapping(columnName = "TARGET_SYSCODE", columnType = 12)
	private String targetSyscode;
	@FieldMapping(columnName = "TRANS_GROUPTYPE", columnType = 12)
	private String transGrouptype;
	@FieldMapping(columnName = "TRANSTASK_CODE", columnType = 12)
	private String transtaskCode;
	@FieldMapping(columnName = "TRANSTASK_CREATETIME", columnType = 93)
	private Timestamp transtaskCreatetime;
	@FieldMapping(columnName = "TRANSTASK_DESC", columnType = 12)
	private String transtaskDesc;
	@FieldMapping(columnName = "TRANSTASK_ENDTIME", columnType = 93)
	private Timestamp transtaskEndtime;
	@FieldMapping(columnName = "TRANSTASK_FIELD1", columnType = 12)
	private String transtaskField1;
	@FieldMapping(columnName = "TRANSTASK_FIELD2", columnType = 12)
	private String transtaskField2;
	@FieldMapping(columnName = "TRANSTASK_FIELD3", columnType = 12)
	private String transtaskField3;
	@FieldMapping(columnName = "TRANSTASK_NAME", columnType = 12)
	private String transtaskName;
	@FieldMapping(columnName = "TRANSTASK_STARTTIME", columnType = 93)
	private Timestamp transtaskStarttime;
	@FieldMapping(columnName = "TRANSTASK_STATUS", columnType = 2)
	private Integer transtaskStatus;
	@FieldMapping(columnName = "TRANSTASK_STATUSDESC", columnType = 12)
	private String transtaskStatusdesc;
	@FieldMapping(columnName = "TRANSTASK_TYPE", columnType = 2)
	private Integer transtaskType;
	
	public PpnTranstask() {
		super();
	}

	public PpnTranstask(String transtaskId) {
		this.transtaskId = transtaskId;
	}

	public PpnTranstask(Timestamp transtaskCreatetime) {
		this.transtaskCreatetime = transtaskCreatetime;
	}

	/**
	 * @return the afdValue
	 */
	public String getAfdValue() {
		return this.afdValue;
	}
	
	/**
	 * @param afdValue the afdValue to set
	 */
	public void setAfdValue(String value) {
		this.afdValue = value;
	}

	/**
	 * @return the audioLang
	 */
	public String getAudioLang() {
		return this.audioLang;
	}
	
	/**
	 * @param audioLang the audioLang to set
	 */
	public void setAudioLang(String value) {
		this.audioLang = value;
	}

	/**
	 * @return the audioType
	 */
	public String getAudioType() {
		return this.audioType;
	}
	
	/**
	 * @param audioType the audioType to set
	 */
	public void setAudioType(String value) {
		this.audioType = value;
	}

	/**
	 * @return the auditTaskcode
	 */
	public String getAuditTaskcode() {
		return this.auditTaskcode;
	}
	
	/**
	 * @param auditTaskcode the auditTaskcode to set
	 */
	public void setAuditTaskcode(String value) {
		this.auditTaskcode = value;
	}

	/**
	 * @return the auditType
	 */
	public Integer getAuditType() {
		return this.auditType;
	}
	
	/**
	 * @param auditType the auditType to set
	 */
	public void setAuditType(Integer value) {
		this.auditType = value;
	}

	/**
	 * @return the clipType
	 */
	public String getClipType() {
		return this.clipType;
	}
	
	/**
	 * @param clipType the clipType to set
	 */
	public void setClipType(String value) {
		this.clipType = value;
	}

	/**
	 * @return the columnCode
	 */
	public String getColumnCode() {
		return this.columnCode;
	}
	
	/**
	 * @param columnCode the columnCode to set
	 */
	public void setColumnCode(String value) {
		this.columnCode = value;
	}

	/**
	 * @return the columnName
	 */
	public String getColumnName() {
		return this.columnName;
	}
	
	/**
	 * @param columnName the columnName to set
	 */
	public void setColumnName(String value) {
		this.columnName = value;
	}

	/**
	 * @return the embTaskcode
	 */
	public String getEmbTaskcode() {
		return this.embTaskcode;
	}
	
	/**
	 * @param embTaskcode the embTaskcode to set
	 */
	public void setEmbTaskcode(String value) {
		this.embTaskcode = value;
	}

	/**
	 * @return the exchTaskcode
	 */
	public String getExchTaskcode() {
		return this.exchTaskcode;
	}
	
	/**
	 * @param exchTaskcode the exchTaskcode to set
	 */
	public void setExchTaskcode(String value) {
		this.exchTaskcode = value;
	}

	/**
	 * @return the extParam
	 */
	public String getExtParam() {
		return this.extParam;
	}
	
	/**
	 * @param extParam the extParam to set
	 */
	public void setExtParam(String value) {
		this.extParam = value;
	}

	/**
	 * @return the flowNumber
	 */
	public Integer getFlowNumber() {
		return this.flowNumber;
	}
	
	/**
	 * @param flowNumber the flowNumber to set
	 */
	public void setFlowNumber(Integer value) {
		this.flowNumber = value;
	}

	/**
	 * @return the materialCode
	 */
	public String getMaterialCode() {
		return this.materialCode;
	}
	
	/**
	 * @param materialCode the materialCode to set
	 */
	public void setMaterialCode(String value) {
		this.materialCode = value;
	}

	/**
	 * @return the materialName
	 */
	public String getMaterialName() {
		return this.materialName;
	}
	
	/**
	 * @param materialName the materialName to set
	 */
	public void setMaterialName(String value) {
		this.materialName = value;
	}

	/**
	 * @return the materialSum
	 */
	public Integer getMaterialSum() {
		return this.materialSum;
	}
	
	/**
	 * @param materialSum the materialSum to set
	 */
	public void setMaterialSum(Integer value) {
		this.materialSum = value;
	}

	/**
	 * @return the materialType
	 */
	public String getMaterialType() {
		return this.materialType;
	}
	
	/**
	 * @param materialType the materialType to set
	 */
	public void setMaterialType(String value) {
		this.materialType = value;
	}

	/**
	 * @return the parentProcexecid
	 */
	public String getParentProcexecid() {
		return this.parentProcexecid;
	}
	
	/**
	 * @param parentProcexecid the parentProcexecid to set
	 */
	public void setParentProcexecid(String value) {
		this.parentProcexecid = value;
	}

	/**
	 * @return the parentTranstaskid
	 */
	public String getParentTranstaskid() {
		return this.parentTranstaskid;
	}
	
	/**
	 * @param parentTranstaskid the parentTranstaskid to set
	 */
	public void setParentTranstaskid(String value) {
		this.parentTranstaskid = value;
	}

	/**
	 * @return the pgmCode
	 */
	public String getPgmCode() {
		return this.pgmCode;
	}
	
	/**
	 * @param pgmCode the pgmCode to set
	 */
	public void setPgmCode(String value) {
		this.pgmCode = value;
	}

	/**
	 * @return the pgmId
	 */
	public String getPgmId() {
		return this.pgmId;
	}
	
	/**
	 * @param pgmId the pgmId to set
	 */
	public void setPgmId(String value) {
		this.pgmId = value;
	}

	/**
	 * @return the pgmName
	 */
	public String getPgmName() {
		return this.pgmName;
	}
	
	/**
	 * @param pgmName the pgmName to set
	 */
	public void setPgmName(String value) {
		this.pgmName = value;
	}

	/**
	 * @return the procexecId
	 */
	public String getProcexecId() {
		return this.procexecId;
	}
	
	/**
	 * @param procexecId the procexecId to set
	 */
	public void setProcexecId(String value) {
		this.procexecId = value;
	}

	/**
	 * @return the prodtaskCode
	 */
	public String getProdtaskCode() {
		return this.prodtaskCode;
	}
	
	/**
	 * @param prodtaskCode the prodtaskCode to set
	 */
	public void setProdtaskCode(String value) {
		this.prodtaskCode = value;
	}

	/**
	 * @return the segmentIndex
	 */
	public Integer getSegmentIndex() {
		return this.segmentIndex;
	}
	
	/**
	 * @param segmentIndex the segmentIndex to set
	 */
	public void setSegmentIndex(Integer value) {
		this.segmentIndex = value;
	}

	/**
	 * @return the srcGrouptype
	 */
	public String getSrcGrouptype() {
		return this.srcGrouptype;
	}
	
	/**
	 * @param srcGrouptype the srcGrouptype to set
	 */
	public void setSrcGrouptype(String value) {
		this.srcGrouptype = value;
	}

	/**
	 * @return the srcSyscode
	 */
	public String getSrcSyscode() {
		return this.srcSyscode;
	}
	
	/**
	 * @param srcSyscode the srcSyscode to set
	 */
	public void setSrcSyscode(String value) {
		this.srcSyscode = value;
	}

	/**
	 * @return the subtitleLang
	 */
	public String getSubtitleLang() {
		return this.subtitleLang;
	}
	
	/**
	 * @param subtitleLang the subtitleLang to set
	 */
	public void setSubtitleLang(String value) {
		this.subtitleLang = value;
	}

	/**
	 * @return the targetAudiocode
	 */
	public String getTargetAudiocode() {
		return this.targetAudiocode;
	}
	
	/**
	 * @param targetAudiocode the targetAudiocode to set
	 */
	public void setTargetAudiocode(String value) {
		this.targetAudiocode = value;
	}

	/**
	 * @return the targetAudioname
	 */
	public String getTargetAudioname() {
		return this.targetAudioname;
	}
	
	/**
	 * @param targetAudioname the targetAudioname to set
	 */
	public void setTargetAudioname(String value) {
		this.targetAudioname = value;
	}

	/**
	 * @return the targetPgmcode
	 */
	public String getTargetPgmcode() {
		return this.targetPgmcode;
	}
	
	/**
	 * @param targetPgmcode the targetPgmcode to set
	 */
	public void setTargetPgmcode(String value) {
		this.targetPgmcode = value;
	}

	/**
	 * @return the targetPgmname
	 */
	public String getTargetPgmname() {
		return this.targetPgmname;
	}
	
	/**
	 * @param targetPgmname the targetPgmname to set
	 */
	public void setTargetPgmname(String value) {
		this.targetPgmname = value;
	}

	/**
	 * @return the targetSubtitleame
	 */
	public String getTargetSubtitleame() {
		return this.targetSubtitleame;
	}
	
	/**
	 * @param targetSubtitleame the targetSubtitleame to set
	 */
	public void setTargetSubtitleame(String value) {
		this.targetSubtitleame = value;
	}

	/**
	 * @return the targetSubtitlecode
	 */
	public String getTargetSubtitlecode() {
		return this.targetSubtitlecode;
	}
	
	/**
	 * @param targetSubtitlecode the targetSubtitlecode to set
	 */
	public void setTargetSubtitlecode(String value) {
		this.targetSubtitlecode = value;
	}

	/**
	 * @return the targetSyscode
	 */
	public String getTargetSyscode() {
		return this.targetSyscode;
	}
	
	/**
	 * @param targetSyscode the targetSyscode to set
	 */
	public void setTargetSyscode(String value) {
		this.targetSyscode = value;
	}

	/**
	 * @return the transGrouptype
	 */
	public String getTransGrouptype() {
		return this.transGrouptype;
	}
	
	/**
	 * @param transGrouptype the transGrouptype to set
	 */
	public void setTransGrouptype(String value) {
		this.transGrouptype = value;
	}

	/**
	 * @return the transtaskCode
	 */
	public String getTranstaskCode() {
		return this.transtaskCode;
	}
	
	/**
	 * @param transtaskCode the transtaskCode to set
	 */
	public void setTranstaskCode(String value) {
		this.transtaskCode = value;
	}

	/**
	 * @return the transtaskCreatetime
	 */
	public Timestamp getTranstaskCreatetime() {
		return this.transtaskCreatetime;
	}
	
	/**
	 * @param transtaskCreatetime the transtaskCreatetime to set
	 */
	public void setTranstaskCreatetime(Timestamp value) {
		this.transtaskCreatetime = value;
	}

	/**
	 * @return the transtaskDesc
	 */
	public String getTranstaskDesc() {
		return this.transtaskDesc;
	}
	
	/**
	 * @param transtaskDesc the transtaskDesc to set
	 */
	public void setTranstaskDesc(String value) {
		this.transtaskDesc = value;
	}

	/**
	 * @return the transtaskEndtime
	 */
	public Timestamp getTranstaskEndtime() {
		return this.transtaskEndtime;
	}
	
	/**
	 * @param transtaskEndtime the transtaskEndtime to set
	 */
	public void setTranstaskEndtime(Timestamp value) {
		this.transtaskEndtime = value;
	}

	/**
	 * @return the transtaskField1
	 */
	public String getTranstaskField1() {
		return this.transtaskField1;
	}
	
	/**
	 * @param transtaskField1 the transtaskField1 to set
	 */
	public void setTranstaskField1(String value) {
		this.transtaskField1 = value;
	}

	/**
	 * @return the transtaskField2
	 */
	public String getTranstaskField2() {
		return this.transtaskField2;
	}
	
	/**
	 * @param transtaskField2 the transtaskField2 to set
	 */
	public void setTranstaskField2(String value) {
		this.transtaskField2 = value;
	}

	/**
	 * @return the transtaskField3
	 */
	public String getTranstaskField3() {
		return this.transtaskField3;
	}
	
	/**
	 * @param transtaskField3 the transtaskField3 to set
	 */
	public void setTranstaskField3(String value) {
		this.transtaskField3 = value;
	}

	/**
	 * @return the transtaskId
	 */
	public String getTranstaskId() {
		return this.transtaskId;
	}
	
	/**
	 * @param transtaskId the transtaskId to set
	 */
	public void setTranstaskId(String value) {
		this.transtaskId = value;
	}

	/**
	 * @return the transtaskName
	 */
	public String getTranstaskName() {
		return this.transtaskName;
	}
	
	/**
	 * @param transtaskName the transtaskName to set
	 */
	public void setTranstaskName(String value) {
		this.transtaskName = value;
	}

	/**
	 * @return the transtaskStarttime
	 */
	public Timestamp getTranstaskStarttime() {
		return this.transtaskStarttime;
	}
	
	/**
	 * @param transtaskStarttime the transtaskStarttime to set
	 */
	public void setTranstaskStarttime(Timestamp value) {
		this.transtaskStarttime = value;
	}

	/**
	 * @return the transtaskStatus
	 */
	public Integer getTranstaskStatus() {
		return this.transtaskStatus;
	}
	
	/**
	 * @param transtaskStatus the transtaskStatus to set
	 */
	public void setTranstaskStatus(Integer value) {
		this.transtaskStatus = value;
	}

	/**
	 * @return the transtaskStatusdesc
	 */
	public String getTranstaskStatusdesc() {
		return this.transtaskStatusdesc;
	}
	
	/**
	 * @param transtaskStatusdesc the transtaskStatusdesc to set
	 */
	public void setTranstaskStatusdesc(String value) {
		this.transtaskStatusdesc = value;
	}

	/**
	 * @return the transtaskType
	 */
	public Integer getTranstaskType() {
		return this.transtaskType;
	}
	
	/**
	 * @param transtaskType the transtaskType to set
	 */
	public void setTranstaskType(Integer value) {
		this.transtaskType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTranstask)) {
			return false;
		}
		PpnTranstask other = (PpnTranstask)o;
		if (null == this.transtaskId) {
			if (other.transtaskId != null)
				return false;
		} else if (!this.transtaskId.equals(other.transtaskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transtaskId == null) ? 0 : transtaskId.hashCode());
		return result;
	}
	
}