/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnTaskFileAv.java
 * 日 期：Fri Jul 29 10:10:03 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_FILE_AV", keyGenerator = "uuid")
public class PpnTaskFileAv implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_A_CHANNEL = "A_CHANNEL";
	public static String PROP_A_DEPTH = "A_DEPTH";
	public static String PROP_A_FORMAT = "A_FORMAT";
	public static String PROP_A_RATE = "A_RATE";
	public static String PROP_A_SAMPLE = "A_SAMPLE";
	public static String PROP_AV_DURATION = "AV_DURATION";
	public static String PROP_AV_FIELD1 = "AV_FIELD1";
	public static String PROP_AV_FIELD2 = "AV_FIELD2";
	public static String PROP_AV_TYPE = "AV_TYPE";
	public static String PROP_FILE_ID = "FILE_ID";
	public static String PROP_V_DEPTH = "V_DEPTH";
	public static String PROP_V_FORMAT = "V_FORMAT";
	public static String PROP_V_RATE = "V_RATE";
	public static String PROP_V_WIDTH_HIGH = "V_WIDTH_HIGH";
	
	/**
	 * primary key field of fileId
	 * foreign key field of PPN_TASK_FILE.FILE_ID
	 */
	@FieldMapping(columnName = "FILE_ID", columnType = 12, primary = true)
	private String fileId;
	@FieldMapping(columnName = "A_CHANNEL", columnType = 12)
	private String aChannel;
	@FieldMapping(columnName = "A_DEPTH", columnType = 12)
	private String aDepth;
	@FieldMapping(columnName = "A_FORMAT", columnType = 12)
	private String aFormat;
	@FieldMapping(columnName = "A_RATE", columnType = 12)
	private String aRate;
	@FieldMapping(columnName = "A_SAMPLE", columnType = 12)
	private String aSample;
	@FieldMapping(columnName = "AV_DURATION", columnType = 12)
	private String avDuration;
	@FieldMapping(columnName = "AV_FIELD1", columnType = 12)
	private String avField1;
	@FieldMapping(columnName = "AV_FIELD2", columnType = 12)
	private String avField2;
	@FieldMapping(columnName = "AV_TYPE", columnType = 2)
	private Integer avType;
	@FieldMapping(columnName = "V_DEPTH", columnType = 12)
	private String vDepth;
	@FieldMapping(columnName = "V_FORMAT", columnType = 12)
	private String vFormat;
	@FieldMapping(columnName = "V_RATE", columnType = 12)
	private String vRate;
	@FieldMapping(columnName = "V_WIDTH_HIGH", columnType = 12)
	private String vWidthHigh;
	
	public PpnTaskFileAv() {
		super();
	}

	public PpnTaskFileAv(String fileId) {
		this.fileId = fileId;
	}

	/**
	 * @return the aChannel
	 */
	public String getAChannel() {
		return this.aChannel;
	}
	
	/**
	 * @param aChannel the aChannel to set
	 */
	public void setAChannel(String value) {
		this.aChannel = value;
	}

	/**
	 * @return the aDepth
	 */
	public String getADepth() {
		return this.aDepth;
	}
	
	/**
	 * @param aDepth the aDepth to set
	 */
	public void setADepth(String value) {
		this.aDepth = value;
	}

	/**
	 * @return the aFormat
	 */
	public String getAFormat() {
		return this.aFormat;
	}
	
	/**
	 * @param aFormat the aFormat to set
	 */
	public void setAFormat(String value) {
		this.aFormat = value;
	}

	/**
	 * @return the aRate
	 */
	public String getARate() {
		return this.aRate;
	}
	
	/**
	 * @param aRate the aRate to set
	 */
	public void setARate(String value) {
		this.aRate = value;
	}

	/**
	 * @return the aSample
	 */
	public String getASample() {
		return this.aSample;
	}
	
	/**
	 * @param aSample the aSample to set
	 */
	public void setASample(String value) {
		this.aSample = value;
	}

	/**
	 * @return the avDuration
	 */
	public String getAvDuration() {
		return this.avDuration;
	}
	
	/**
	 * @param avDuration the avDuration to set
	 */
	public void setAvDuration(String value) {
		this.avDuration = value;
	}

	/**
	 * @return the avField1
	 */
	public String getAvField1() {
		return this.avField1;
	}
	
	/**
	 * @param avField1 the avField1 to set
	 */
	public void setAvField1(String value) {
		this.avField1 = value;
	}

	/**
	 * @return the avField2
	 */
	public String getAvField2() {
		return this.avField2;
	}
	
	/**
	 * @param avField2 the avField2 to set
	 */
	public void setAvField2(String value) {
		this.avField2 = value;
	}

	/**
	 * @return the avType
	 */
	public Integer getAvType() {
		return this.avType;
	}
	
	/**
	 * @param avType the avType to set
	 */
	public void setAvType(Integer value) {
		this.avType = value;
	}

	/**
	 * @return the fileId
	 */
	public String getFileId() {
		return this.fileId;
	}
	
	/**
	 * @param fileId the fileId to set
	 */
	public void setFileId(String value) {
		this.fileId = value;
	}

	/**
	 * @return the vDepth
	 */
	public String getVDepth() {
		return this.vDepth;
	}
	
	/**
	 * @param vDepth the vDepth to set
	 */
	public void setVDepth(String value) {
		this.vDepth = value;
	}

	/**
	 * @return the vFormat
	 */
	public String getVFormat() {
		return this.vFormat;
	}
	
	/**
	 * @param vFormat the vFormat to set
	 */
	public void setVFormat(String value) {
		this.vFormat = value;
	}

	/**
	 * @return the vRate
	 */
	public String getVRate() {
		return this.vRate;
	}
	
	/**
	 * @param vRate the vRate to set
	 */
	public void setVRate(String value) {
		this.vRate = value;
	}

	/**
	 * @return the vWidthHigh
	 */
	public String getVWidthHigh() {
		return this.vWidthHigh;
	}
	
	/**
	 * @param vWidthHigh the vWidthHigh to set
	 */
	public void setVWidthHigh(String value) {
		this.vWidthHigh = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskFileAv)) {
			return false;
		}
		PpnTaskFileAv other = (PpnTaskFileAv)o;
		if (null == this.fileId) {
			if (other.fileId != null)
				return false;
		} else if (!this.fileId.equals(other.fileId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fileId == null) ? 0 : fileId.hashCode());
		return result;
	}
	
}