/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnTaskAudio.java
 * 日 期：Thu Oct 13 16:15:01 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_AUDIO", keyGenerator = "uuid")
public class PpnTaskAudio implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AUDIO_FIELD1 = "AUDIO_FIELD1";
	public static String PROP_AUDIO_FIELD2 = "AUDIO_FIELD2";
	public static String PROP_DESTINATIONS = "DESTINATIONS";
	public static String PROP_PROD_DURATION = "PROD_DURATION";
	public static String PROP_PROD_SCALE = "PROD_SCALE";
	public static String PROP_REF_VIDEO = "REF_VIDEO";
	public static String PROP_ROOM_QUOTA = "ROOM_QUOTA";
	public static String PROP_SHARE_QUOTA = "SHARE_QUOTA";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_USER_LIST = "USER_LIST";
	public static String PROP_VIDEO_CODE_RATE = "VIDEO_CODE_RATE";
	public static String PROP_VIDEO_DURATION = "VIDEO_DURATION";
	public static String PROP_WORK_TYPE = "WORK_TYPE";
	
	/**
	 * primary key field of taskId
	 * foreign key field of PPN_TASK.TASK_ID
	 */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "AUDIO_FIELD1", columnType = 12)
	private String audioField1;
	@FieldMapping(columnName = "AUDIO_FIELD2", columnType = 12)
	private String audioField2;
	@FieldMapping(columnName = "DESTINATIONS", columnType = 12)
	private String destinations;
	@FieldMapping(columnName = "PROD_DURATION", columnType = 12)
	private String prodDuration;
	@FieldMapping(columnName = "PROD_SCALE", columnType = 12)
	private String prodScale;
	@FieldMapping(columnName = "REF_VIDEO", columnType = 2)
	private Integer refVideo;
	@FieldMapping(columnName = "ROOM_QUOTA", columnType = 12)
	private String roomQuota;
	@FieldMapping(columnName = "SHARE_QUOTA", columnType = 12)
	private String shareQuota;
	@FieldMapping(columnName = "USER_LIST", columnType = 12)
	private String userList;
	@FieldMapping(columnName = "VIDEO_CODE_RATE", columnType = 12)
	private String videoCodeRate;
	@FieldMapping(columnName = "VIDEO_DURATION", columnType = 12)
	private String videoDuration;
	@FieldMapping(columnName = "WORK_TYPE", columnType = 12)
	private String workType;
	
	public PpnTaskAudio() {
		super();
	}

	public PpnTaskAudio(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * @return the audioField1
	 */
	public String getAudioField1() {
		return this.audioField1;
	}
	
	/**
	 * @param audioField1 the audioField1 to set
	 */
	public void setAudioField1(String value) {
		this.audioField1 = value;
	}

	/**
	 * @return the audioField2
	 */
	public String getAudioField2() {
		return this.audioField2;
	}
	
	/**
	 * @param audioField2 the audioField2 to set
	 */
	public void setAudioField2(String value) {
		this.audioField2 = value;
	}

	/**
	 * @return the destinations
	 */
	public String getDestinations() {
		return this.destinations;
	}
	
	/**
	 * @param destinations the destinations to set
	 */
	public void setDestinations(String value) {
		this.destinations = value;
	}

	/**
	 * @return the prodDuration
	 */
	public String getProdDuration() {
		return this.prodDuration;
	}
	
	/**
	 * @param prodDuration the prodDuration to set
	 */
	public void setProdDuration(String value) {
		this.prodDuration = value;
	}

	/**
	 * @return the prodScale
	 */
	public String getProdScale() {
		return this.prodScale;
	}
	
	/**
	 * @param prodScale the prodScale to set
	 */
	public void setProdScale(String value) {
		this.prodScale = value;
	}

	/**
	 * @return the refVideo
	 */
	public Integer getRefVideo() {
		return this.refVideo;
	}
	
	/**
	 * @param refVideo the refVideo to set
	 */
	public void setRefVideo(Integer value) {
		this.refVideo = value;
	}

	/**
	 * @return the roomQuota
	 */
	public String getRoomQuota() {
		return this.roomQuota;
	}
	
	/**
	 * @param roomQuota the roomQuota to set
	 */
	public void setRoomQuota(String value) {
		this.roomQuota = value;
	}

	/**
	 * @return the shareQuota
	 */
	public String getShareQuota() {
		return this.shareQuota;
	}
	
	/**
	 * @param shareQuota the shareQuota to set
	 */
	public void setShareQuota(String value) {
		this.shareQuota = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/**
	 * @return the userList
	 */
	public String getUserList() {
		return this.userList;
	}
	
	/**
	 * @param userList the userList to set
	 */
	public void setUserList(String value) {
		this.userList = value;
	}

	/**
	 * @return the videoCodeRate
	 */
	public String getVideoCodeRate() {
		return this.videoCodeRate;
	}
	
	/**
	 * @param videoCodeRate the videoCodeRate to set
	 */
	public void setVideoCodeRate(String value) {
		this.videoCodeRate = value;
	}

	/**
	 * @return the videoDuration
	 */
	public String getVideoDuration() {
		return this.videoDuration;
	}
	
	/**
	 * @param videoDuration the videoDuration to set
	 */
	public void setVideoDuration(String value) {
		this.videoDuration = value;
	}

	/**
	 * @return the workType
	 */
	public String getWorkType() {
		return this.workType;
	}
	
	/**
	 * @param workType the workType to set
	 */
	public void setWorkType(String value) {
		this.workType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskAudio)) {
			return false;
		}
		PpnTaskAudio other = (PpnTaskAudio)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}