/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnTaskPhaseDef.java
 * 日 期：Wed Aug 31 21:06:25 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_PHASE_DEF", keyGenerator = "uuid")
public class PpnTaskPhaseDef implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_PHASE_CODE = "PHASE_CODE";
	public static String PROP_PHASE_DEF_ID = "PHASE_DEF_ID";
	public static String PROP_PHASE_DEF_STATUS = "PHASE_DEF_STATUS";
	public static String PROP_PHASE_DESC = "PHASE_DESC";
	public static String PROP_PHASE_FIELD1 = "PHASE_FIELD1";
	public static String PROP_PHASE_FIELD2 = "PHASE_FIELD2";
	public static String PROP_PHASE_INDEX = "PHASE_INDEX";
	public static String PROP_PHASE_NAME = "PHASE_NAME";
	public static String PROP_PHASE_TYPE = "PHASE_TYPE";
	public static String PROP_PHASE_URL = "PHASE_URL";
	
	/** primary key field of phaseDefId */
	@FieldMapping(columnName = "PHASE_DEF_ID", columnType = 12, primary = true)
	private String phaseDefId;
	@FieldMapping(columnName = "PHASE_CODE", columnType = 12)
	private String phaseCode;
	@FieldMapping(columnName = "PHASE_DEF_STATUS", columnType = 2)
	private Integer phaseDefStatus;
	@FieldMapping(columnName = "PHASE_DESC", columnType = 12)
	private String phaseDesc;
	@FieldMapping(columnName = "PHASE_FIELD1", columnType = 12)
	private String phaseField1;
	@FieldMapping(columnName = "PHASE_FIELD2", columnType = 12)
	private String phaseField2;
	@FieldMapping(columnName = "PHASE_INDEX", columnType = 2)
	private Integer phaseIndex;
	@FieldMapping(columnName = "PHASE_NAME", columnType = 12)
	private String phaseName;
	@FieldMapping(columnName = "PHASE_TYPE", columnType = 12)
	private String phaseType;
	@FieldMapping(columnName = "PHASE_URL", columnType = 12)
	private String phaseUrl;
	
	public PpnTaskPhaseDef() {
		super();
	}

	public PpnTaskPhaseDef(String phaseDefId) {
		this.phaseDefId = phaseDefId;
	}

	/**
	 * @return the phaseCode
	 */
	public String getPhaseCode() {
		return this.phaseCode;
	}
	
	/**
	 * @param phaseCode the phaseCode to set
	 */
	public void setPhaseCode(String value) {
		this.phaseCode = value;
	}

	/**
	 * @return the phaseDefId
	 */
	public String getPhaseDefId() {
		return this.phaseDefId;
	}
	
	/**
	 * @param phaseDefId the phaseDefId to set
	 */
	public void setPhaseDefId(String value) {
		this.phaseDefId = value;
	}

	/**
	 * @return the phaseDefStatus
	 */
	public Integer getPhaseDefStatus() {
		return this.phaseDefStatus;
	}
	
	/**
	 * @param phaseDefStatus the phaseDefStatus to set
	 */
	public void setPhaseDefStatus(Integer value) {
		this.phaseDefStatus = value;
	}

	/**
	 * @return the phaseDesc
	 */
	public String getPhaseDesc() {
		return this.phaseDesc;
	}
	
	/**
	 * @param phaseDesc the phaseDesc to set
	 */
	public void setPhaseDesc(String value) {
		this.phaseDesc = value;
	}

	/**
	 * @return the phaseField1
	 */
	public String getPhaseField1() {
		return this.phaseField1;
	}
	
	/**
	 * @param phaseField1 the phaseField1 to set
	 */
	public void setPhaseField1(String value) {
		this.phaseField1 = value;
	}

	/**
	 * @return the phaseField2
	 */
	public String getPhaseField2() {
		return this.phaseField2;
	}
	
	/**
	 * @param phaseField2 the phaseField2 to set
	 */
	public void setPhaseField2(String value) {
		this.phaseField2 = value;
	}

	/**
	 * @return the phaseIndex
	 */
	public Integer getPhaseIndex() {
		return this.phaseIndex;
	}
	
	/**
	 * @param phaseIndex the phaseIndex to set
	 */
	public void setPhaseIndex(Integer value) {
		this.phaseIndex = value;
	}

	/**
	 * @return the phaseName
	 */
	public String getPhaseName() {
		return this.phaseName;
	}
	
	/**
	 * @param phaseName the phaseName to set
	 */
	public void setPhaseName(String value) {
		this.phaseName = value;
	}

	/**
	 * @return the phaseType
	 */
	public String getPhaseType() {
		return this.phaseType;
	}
	
	/**
	 * @param phaseType the phaseType to set
	 */
	public void setPhaseType(String value) {
		this.phaseType = value;
	}

	/**
	 * @return the phaseUrl
	 */
	public String getPhaseUrl() {
		return this.phaseUrl;
	}
	
	/**
	 * @param phaseUrl the phaseUrl to set
	 */
	public void setPhaseUrl(String value) {
		this.phaseUrl = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskPhaseDef)) {
			return false;
		}
		PpnTaskPhaseDef other = (PpnTaskPhaseDef)o;
		if (null == this.phaseDefId) {
			if (other.phaseDefId != null)
				return false;
		} else if (!this.phaseDefId.equals(other.phaseDefId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((phaseDefId == null) ? 0 : phaseDefId.hashCode());
		return result;
	}
	
}