/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.beans.PpnTsbTask.java
 * 日 期：Sat Oct 15 19:48:31 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TSB_TASK", keyGenerator = "uuid")
public class PpnTsbTask implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AUDIT_RULE_PARAM = "AUDIT_RULE_PARAM";
	public static String PROP_BOOK_CODE = "BOOK_CODE";
	public static String PROP_CLIP_TYPE = "CLIP_TYPE";
	public static String PROP_CREATER_USERCODE = "CREATER_USERCODE";
	public static String PROP_EXCH_TASKCODE = "EXCH_TASKCODE";
	public static String PROP_FLOW_SEQUENCE = "FLOW_SEQUENCE";
	public static String PROP_MATERIAL_CODE = "MATERIAL_CODE";
	public static String PROP_MATERIAL_NAME = "MATERIAL_NAME";
	public static String PROP_MATERIAL_TYPE = "MATERIAL_TYPE";
	public static String PROP_MTS_TASK_GROUP = "MTS_TASK_GROUP";
	public static String PROP_PGM_ID = "PGM_ID";
	public static String PROP_PRODTASK_CODE = "PRODTASK_CODE";
	public static String PROP_PUSH_TARGET_SYSCODE = "PUSH_TARGET_SYSCODE";
	public static String PROP_SEGMENT_INDEX = "SEGMENT_INDEX";
	public static String PROP_SRC_SYSCODE = "SRC_SYSCODE";
	public static String PROP_STUDIO_PARAM = "STUDIO_PARAM";
	public static String PROP_TARGET_SEGMENT_INDEX = "TARGET_SEGMENT_INDEX";
	public static String PROP_TARGET_SYSCODE = "TARGET_SYSCODE";
	public static String PROP_TARGET_TYPE = "TARGET_TYPE";
	public static String PROP_TASK_CREATE_TIME = "TASK_CREATE_TIME";
	public static String PROP_TASK_DESC = "TASK_DESC";
	public static String PROP_TASK_EXT_PARAM = "TASK_EXT_PARAM";
	public static String PROP_TASK_FIELD1 = "TASK_FIELD1";
	public static String PROP_TASK_FIELD2 = "TASK_FIELD2";
	public static String PROP_TASK_FIELD3 = "TASK_FIELD3";
	public static String PROP_TASK_FINSH_TIME = "TASK_FINSH_TIME";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_NAME = "TASK_NAME";
	public static String PROP_TASK_STATUS = "TASK_STATUS";
	public static String PROP_TASK_TYPE = "TASK_TYPE";
	public static String PROP_TRANSTASK_ID = "TRANSTASK_ID";
	public static String PROP_TRANS_TYPE = "TRANS_TYPE";
	
	/** primary key field of taskId */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "AUDIT_RULE_PARAM", columnType = 12)
	private String auditRuleParam;
	@FieldMapping(columnName = "BOOK_CODE", columnType = 12)
	private String bookCode;
	@FieldMapping(columnName = "CLIP_TYPE", columnType = 12)
	private String clipType;
	@FieldMapping(columnName = "CREATER_USERCODE", columnType = 12)
	private String createrUsercode;
	@FieldMapping(columnName = "EXCH_TASKCODE", columnType = 12)
	private String exchTaskcode;
	@FieldMapping(columnName = "FLOW_SEQUENCE", columnType = 2)
	private Integer flowSequence;
	@FieldMapping(columnName = "MATERIAL_CODE", columnType = 12)
	private String materialCode;
	@FieldMapping(columnName = "MATERIAL_NAME", columnType = 12)
	private String materialName;
	@FieldMapping(columnName = "MATERIAL_TYPE", columnType = 12)
	private String materialType;
	@FieldMapping(columnName = "MTS_TASK_GROUP", columnType = 12)
	private String mtsTaskGroup;
	@FieldMapping(columnName = "PGM_ID", columnType = 12)
	private String pgmId;
	@FieldMapping(columnName = "PRODTASK_CODE", columnType = 12)
	private String prodtaskCode;
	@FieldMapping(columnName = "PUSH_TARGET_SYSCODE", columnType = 12)
	private String pushTargetSyscode;
	@FieldMapping(columnName = "SEGMENT_INDEX", columnType = 2)
	private Integer segmentIndex;
	@FieldMapping(columnName = "SRC_SYSCODE", columnType = 12)
	private String srcSyscode;
	@FieldMapping(columnName = "STUDIO_PARAM", columnType = 12)
	private String studioParam;
	@FieldMapping(columnName = "TARGET_SEGMENT_INDEX", columnType = 2)
	private Integer targetSegmentIndex;
	@FieldMapping(columnName = "TARGET_SYSCODE", columnType = 12)
	private String targetSyscode;
	@FieldMapping(columnName = "TARGET_TYPE", columnType = 2)
	private Integer targetType;
	@FieldMapping(columnName = "TASK_CREATE_TIME", columnType = 93)
	private Date taskCreateTime;
	@FieldMapping(columnName = "TASK_DESC", columnType = 12)
	private String taskDesc;
	@FieldMapping(columnName = "TASK_EXT_PARAM", columnType = 12)
	private String taskExtParam;
	@FieldMapping(columnName = "TASK_FIELD1", columnType = 12)
	private String taskField1;
	@FieldMapping(columnName = "TASK_FIELD2", columnType = 12)
	private String taskField2;
	@FieldMapping(columnName = "TASK_FIELD3", columnType = 12)
	private String taskField3;
	@FieldMapping(columnName = "TASK_FINSH_TIME", columnType = 93)
	private Date taskFinshTime;
	@FieldMapping(columnName = "TASK_NAME", columnType = 12)
	private String taskName;
	@FieldMapping(columnName = "TASK_STATUS", columnType = 2)
	private Integer taskStatus;
	@FieldMapping(columnName = "TASK_TYPE", columnType = 2)
	private Integer taskType;
	@FieldMapping(columnName = "TRANSTASK_ID", columnType = 12)
	private String transtaskId;
	@FieldMapping(columnName = "TRANS_TYPE", columnType = 2)
	private Integer transType;
	
	public PpnTsbTask() {
		super();
	}

	public PpnTsbTask(String taskId) {
		this.taskId = taskId;
	}

	public PpnTsbTask(Date taskCreateTime, String taskName) {
		this.taskCreateTime = taskCreateTime;
		this.taskName = taskName;
	}

	/**
	 * @return the auditRuleParam
	 */
	public String getAuditRuleParam() {
		return this.auditRuleParam;
	}
	
	/**
	 * @param auditRuleParam the auditRuleParam to set
	 */
	public void setAuditRuleParam(String value) {
		this.auditRuleParam = value;
	}

	/**
	 * @return the bookCode
	 */
	public String getBookCode() {
		return this.bookCode;
	}
	
	/**
	 * @param bookCode the bookCode to set
	 */
	public void setBookCode(String value) {
		this.bookCode = value;
	}

	/**
	 * @return the clipType
	 */
	public String getClipType() {
		return this.clipType;
	}
	
	/**
	 * @param clipType the clipType to set
	 */
	public void setClipType(String value) {
		this.clipType = value;
	}

	/**
	 * @return the createrUsercode
	 */
	public String getCreaterUsercode() {
		return this.createrUsercode;
	}
	
	/**
	 * @param createrUsercode the createrUsercode to set
	 */
	public void setCreaterUsercode(String value) {
		this.createrUsercode = value;
	}

	/**
	 * @return the exchTaskcode
	 */
	public String getExchTaskcode() {
		return this.exchTaskcode;
	}
	
	/**
	 * @param exchTaskcode the exchTaskcode to set
	 */
	public void setExchTaskcode(String value) {
		this.exchTaskcode = value;
	}

	/**
	 * @return the flowSequence
	 */
	public Integer getFlowSequence() {
		return this.flowSequence;
	}
	
	/**
	 * @param flowSequence the flowSequence to set
	 */
	public void setFlowSequence(Integer value) {
		this.flowSequence = value;
	}

	/**
	 * @return the materialCode
	 */
	public String getMaterialCode() {
		return this.materialCode;
	}
	
	/**
	 * @param materialCode the materialCode to set
	 */
	public void setMaterialCode(String value) {
		this.materialCode = value;
	}

	/**
	 * @return the materialName
	 */
	public String getMaterialName() {
		return this.materialName;
	}
	
	/**
	 * @param materialName the materialName to set
	 */
	public void setMaterialName(String value) {
		this.materialName = value;
	}

	/**
	 * @return the materialType
	 */
	public String getMaterialType() {
		return this.materialType;
	}
	
	/**
	 * @param materialType the materialType to set
	 */
	public void setMaterialType(String value) {
		this.materialType = value;
	}

	/**
	 * @return the mtsTaskGroup
	 */
	public String getMtsTaskGroup() {
		return this.mtsTaskGroup;
	}
	
	/**
	 * @param mtsTaskGroup the mtsTaskGroup to set
	 */
	public void setMtsTaskGroup(String value) {
		this.mtsTaskGroup = value;
	}

	/**
	 * @return the pgmId
	 */
	public String getPgmId() {
		return this.pgmId;
	}
	
	/**
	 * @param pgmId the pgmId to set
	 */
	public void setPgmId(String value) {
		this.pgmId = value;
	}

	/**
	 * @return the prodtaskCode
	 */
	public String getProdtaskCode() {
		return this.prodtaskCode;
	}
	
	/**
	 * @param prodtaskCode the prodtaskCode to set
	 */
	public void setProdtaskCode(String value) {
		this.prodtaskCode = value;
	}

	/**
	 * @return the pushTargetSyscode
	 */
	public String getPushTargetSyscode() {
		return this.pushTargetSyscode;
	}
	
	/**
	 * @param pushTargetSyscode the pushTargetSyscode to set
	 */
	public void setPushTargetSyscode(String value) {
		this.pushTargetSyscode = value;
	}

	/**
	 * @return the segmentIndex
	 */
	public Integer getSegmentIndex() {
		return this.segmentIndex;
	}
	
	/**
	 * @param segmentIndex the segmentIndex to set
	 */
	public void setSegmentIndex(Integer value) {
		this.segmentIndex = value;
	}

	/**
	 * @return the srcSyscode
	 */
	public String getSrcSyscode() {
		return this.srcSyscode;
	}
	
	/**
	 * @param srcSyscode the srcSyscode to set
	 */
	public void setSrcSyscode(String value) {
		this.srcSyscode = value;
	}

	/**
	 * @return the studioParam
	 */
	public String getStudioParam() {
		return this.studioParam;
	}
	
	/**
	 * @param studioParam the studioParam to set
	 */
	public void setStudioParam(String value) {
		this.studioParam = value;
	}

	/**
	 * @return the targetSegmentIndex
	 */
	public Integer getTargetSegmentIndex() {
		return this.targetSegmentIndex;
	}
	
	/**
	 * @param targetSegmentIndex the targetSegmentIndex to set
	 */
	public void setTargetSegmentIndex(Integer value) {
		this.targetSegmentIndex = value;
	}

	/**
	 * @return the targetSyscode
	 */
	public String getTargetSyscode() {
		return this.targetSyscode;
	}
	
	/**
	 * @param targetSyscode the targetSyscode to set
	 */
	public void setTargetSyscode(String value) {
		this.targetSyscode = value;
	}

	/**
	 * @return the targetType
	 */
	public Integer getTargetType() {
		return this.targetType;
	}
	
	/**
	 * @param targetType the targetType to set
	 */
	public void setTargetType(Integer value) {
		this.targetType = value;
	}

	/**
	 * @return the taskCreateTime
	 */
	public Date getTaskCreateTime() {
		return this.taskCreateTime;
	}
	
	/**
	 * @param taskCreateTime the taskCreateTime to set
	 */
	public void setTaskCreateTime(Date value) {
		this.taskCreateTime = value;
	}

	/**
	 * @return the taskDesc
	 */
	public String getTaskDesc() {
		return this.taskDesc;
	}
	
	/**
	 * @param taskDesc the taskDesc to set
	 */
	public void setTaskDesc(String value) {
		this.taskDesc = value;
	}

	/**
	 * @return the taskExtParam
	 */
	public String getTaskExtParam() {
		return this.taskExtParam;
	}
	
	/**
	 * @param taskExtParam the taskExtParam to set
	 */
	public void setTaskExtParam(String value) {
		this.taskExtParam = value;
	}

	/**
	 * @return the taskField1
	 */
	public String getTaskField1() {
		return this.taskField1;
	}
	
	/**
	 * @param taskField1 the taskField1 to set
	 */
	public void setTaskField1(String value) {
		this.taskField1 = value;
	}

	/**
	 * @return the taskField2
	 */
	public String getTaskField2() {
		return this.taskField2;
	}
	
	/**
	 * @param taskField2 the taskField2 to set
	 */
	public void setTaskField2(String value) {
		this.taskField2 = value;
	}

	/**
	 * @return the taskField3
	 */
	public String getTaskField3() {
		return this.taskField3;
	}
	
	/**
	 * @param taskField3 the taskField3 to set
	 */
	public void setTaskField3(String value) {
		this.taskField3 = value;
	}

	/**
	 * @return the taskFinshTime
	 */
	public Date getTaskFinshTime() {
		return this.taskFinshTime;
	}
	
	/**
	 * @param taskFinshTime the taskFinshTime to set
	 */
	public void setTaskFinshTime(Date value) {
		this.taskFinshTime = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return this.taskName;
	}
	
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String value) {
		this.taskName = value;
	}

	/**
	 * @return the taskStatus
	 */
	public Integer getTaskStatus() {
		return this.taskStatus;
	}
	
	/**
	 * @param taskStatus the taskStatus to set
	 */
	public void setTaskStatus(Integer value) {
		this.taskStatus = value;
	}

	/**
	 * @return the taskType
	 */
	public Integer getTaskType() {
		return this.taskType;
	}
	
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(Integer value) {
		this.taskType = value;
	}

	/**
	 * @return the transtaskId
	 */
	public String getTranstaskId() {
		return this.transtaskId;
	}
	
	/**
	 * @param transtaskId the transtaskId to set
	 */
	public void setTranstaskId(String value) {
		this.transtaskId = value;
	}

	/**
	 * @return the transType
	 */
	public Integer getTransType() {
		return this.transType;
	}
	
	/**
	 * @param transType the transType to set
	 */
	public void setTransType(Integer value) {
		this.transType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTsbTask)) {
			return false;
		}
		PpnTsbTask other = (PpnTsbTask)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}