/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnTaskMember.java
 * 日 期：Fri Jul 29 10:10:03 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_MEMBER", keyGenerator = "uuid")
public class PpnTaskMember implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_MEMB_CREATE_TIME = "MEMB_CREATE_TIME";
	public static String PROP_MEMB_CREATE_USER = "MEMB_CREATE_USER";
	public static String PROP_MEMB__FIELD1 = "MEMB__FIELD1";
	public static String PROP_MEMB_ID = "MEMB_ID";
	public static String PROP_MEMB_ROLE = "MEMB_ROLE";
	public static String PROP_MEMB_STATUS = "MEMB_STATUS";
	public static String PROP_MEMB_USER_CODE = "MEMB_USER_CODE";
	public static String PROP_TASK_ID = "TASK_ID";
	
	/** primary key field of membId */
	@FieldMapping(columnName = "MEMB_ID", columnType = 12, primary = true)
	private String membId;
	@FieldMapping(columnName = "MEMB_CREATE_TIME", columnType = 93)
	private Date membCreateTime;
	@FieldMapping(columnName = "MEMB_CREATE_USER", columnType = 12)
	private String membCreateUser;
	@FieldMapping(columnName = "MEMB__FIELD1", columnType = 12)
	private String membField1;
	@FieldMapping(columnName = "MEMB_ROLE", columnType = 12)
	private String membRole;
	@FieldMapping(columnName = "MEMB_STATUS", columnType = 2)
	private Integer membStatus;
	@FieldMapping(columnName = "MEMB_USER_CODE", columnType = 12)
	private String membUserCode;
	/** foreign key field of PPN_TASK.TASK_ID */
	@FieldMapping(columnName = "TASK_ID", columnType = 12)
	private String taskId;
	
	public PpnTaskMember() {
		super();
	}

	public PpnTaskMember(String membId) {
		this.membId = membId;
	}

	public PpnTaskMember(String membUserCode, String taskId) {
		this.membUserCode = membUserCode;
		this.taskId = taskId;
	}

	/**
	 * @return the membCreateTime
	 */
	public Date getMembCreateTime() {
		return this.membCreateTime;
	}
	
	/**
	 * @param membCreateTime the membCreateTime to set
	 */
	public void setMembCreateTime(Date value) {
		this.membCreateTime = value;
	}

	/**
	 * @return the membCreateUser
	 */
	public String getMembCreateUser() {
		return this.membCreateUser;
	}
	
	/**
	 * @param membCreateUser the membCreateUser to set
	 */
	public void setMembCreateUser(String value) {
		this.membCreateUser = value;
	}

	/**
	 * @return the membField1
	 */
	public String getMembField1() {
		return this.membField1;
	}
	
	/**
	 * @param membField1 the membField1 to set
	 */
	public void setMembField1(String value) {
		this.membField1 = value;
	}

	/**
	 * @return the membId
	 */
	public String getMembId() {
		return this.membId;
	}
	
	/**
	 * @param membId the membId to set
	 */
	public void setMembId(String value) {
		this.membId = value;
	}

	/**
	 * @return the membRole
	 */
	public String getMembRole() {
		return this.membRole;
	}
	
	/**
	 * @param membRole the membRole to set
	 */
	public void setMembRole(String value) {
		this.membRole = value;
	}

	/**
	 * @return the membStatus
	 */
	public Integer getMembStatus() {
		return this.membStatus;
	}
	
	/**
	 * @param membStatus the membStatus to set
	 */
	public void setMembStatus(Integer value) {
		this.membStatus = value;
	}

	/**
	 * @return the membUserCode
	 */
	public String getMembUserCode() {
		return this.membUserCode;
	}
	
	/**
	 * @param membUserCode the membUserCode to set
	 */
	public void setMembUserCode(String value) {
		this.membUserCode = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskMember)) {
			return false;
		}
		PpnTaskMember other = (PpnTaskMember)o;
		if (null == this.membId) {
			if (other.membId != null)
				return false;
		} else if (!this.membId.equals(other.membId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((membId == null) ? 0 : membId.hashCode());
		return result;
	}
	
}