/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnTaskCata2File.java
 * 日 期：Fri Jul 29 10:10:02 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_CATA_2_FILE", keyGenerator = "uuid")
public class PpnTaskCata2File implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_C2F_ID = "C2F_ID";
	public static String PROP_CLIP_CATA_ID = "CLIP_CATA_ID";
	public static String PROP_FILE_ID = "FILE_ID";
	
	/** primary key field of c2fId */
	@FieldMapping(columnName = "C2F_ID", columnType = 12, primary = true)
	private String c2fId;
	/** foreign key field of PPN_TASK_CATA.CLIP_CATA_ID */
	@FieldMapping(columnName = "CLIP_CATA_ID", columnType = 12)
	private String clipCataId;
	@FieldMapping(columnName = "FILE_ID", columnType = 12)
	private String fileId;
	
	public PpnTaskCata2File() {
		super();
	}

	public PpnTaskCata2File(String c2fId) {
		this.c2fId = c2fId;
	}

	/**
	 * @return the c2fId
	 */
	public String getC2fId() {
		return this.c2fId;
	}
	
	/**
	 * @param c2fId the c2fId to set
	 */
	public void setC2fId(String value) {
		this.c2fId = value;
	}

	/**
	 * @return the clipCataId
	 */
	public String getClipCataId() {
		return this.clipCataId;
	}
	
	/**
	 * @param clipCataId the clipCataId to set
	 */
	public void setClipCataId(String value) {
		this.clipCataId = value;
	}

	/**
	 * @return the fileId
	 */
	public String getFileId() {
		return this.fileId;
	}
	
	/**
	 * @param fileId the fileId to set
	 */
	public void setFileId(String value) {
		this.fileId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskCata2File)) {
			return false;
		}
		PpnTaskCata2File other = (PpnTaskCata2File)o;
		if (null == this.c2fId) {
			if (other.c2fId != null)
				return false;
		} else if (!this.c2fId.equals(other.c2fId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((c2fId == null) ? 0 : c2fId.hashCode());
		return result;
	}
	
}