/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jue2.trm.bean.PpnTaskFileCata.java
 * 日 期：Mon Aug 01 14:33:14 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_FILE_CATA", keyGenerator = "uuid")
public class PpnTaskFileCata implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CATA_AUDIO = "CATA_AUDIO";
	public static String PROP_CATA_DURATION = "CATA_DURATION";
	public static String PROP_CATA_FIELD1 = "CATA_FIELD1";
	public static String PROP_CATA_FIELD2 = "CATA_FIELD2";
	public static String PROP_CATA_ID = "CATA_ID";
	public static String PROP_CATA_KEYWORDS = "CATA_KEYWORDS";
	public static String PROP_CATA_PGM_CODE = "CATA_PGM_CODE";
	public static String PROP_CATA_SHOOTING_PLACE = "CATA_SHOOTING_PLACE";
	public static String PROP_CATA_SHOOTING_USER = "CATA_SHOOTING_USER";
	public static String PROP_CATA_SIGN = "CATA_SIGN";
	public static String PROP_CATA_TIME = "CATA_TIME";
	public static String PROP_CATA_USER = "CATA_USER";
	public static String PROP_CATA_VIDEO = "CATA_VIDEO";
	public static String PROP_CATA_WHAT = "CATA_WHAT";
	public static String PROP_CATA_WHEN = "CATA_WHEN";
	public static String PROP_CATA_WHERE = "CATA_WHERE";
	public static String PROP_CATA_WHO = "CATA_WHO";
	
	/** primary key field of cataId */
	@FieldMapping(columnName = "CATA_ID", columnType = 12, primary = true)
	private String cataId;
	@FieldMapping(columnName = "CATA_AUDIO", columnType = 12)
	private String cataAudio;
	@FieldMapping(columnName = "CATA_DURATION", columnType = 12)
	private String cataDuration;
	@FieldMapping(columnName = "CATA_FIELD1", columnType = 12)
	private String cataField1;
	@FieldMapping(columnName = "CATA_FIELD2", columnType = 12)
	private String cataField2;
	@FieldMapping(columnName = "CATA_KEYWORDS", columnType = 12)
	private String cataKeywords;
	@FieldMapping(columnName = "CATA_PGM_CODE", columnType = 12)
	private String cataPgmCode;
	@FieldMapping(columnName = "CATA_SHOOTING_PLACE", columnType = 12)
	private String cataShootingPlace;
	@FieldMapping(columnName = "CATA_SHOOTING_USER", columnType = 12)
	private String cataShootingUser;
	@FieldMapping(columnName = "CATA_SIGN", columnType = 2)
	private Integer cataSign;
	@FieldMapping(columnName = "CATA_TIME", columnType = 12)
	private String cataTime;
	@FieldMapping(columnName = "CATA_USER", columnType = 12)
	private String cataUser;
	@FieldMapping(columnName = "CATA_VIDEO", columnType = 12)
	private String cataVideo;
	@FieldMapping(columnName = "CATA_WHAT", columnType = 12)
	private String cataWhat;
	@FieldMapping(columnName = "CATA_WHEN", columnType = 93)
	private Date cataWhen;
	@FieldMapping(columnName = "CATA_WHERE", columnType = 12)
	private String cataWhere;
	@FieldMapping(columnName = "CATA_WHO", columnType = 12)
	private String cataWho;
	
	public PpnTaskFileCata() {
		super();
	}

	public PpnTaskFileCata(String cataId) {
		this.cataId = cataId;
	}

	/**
	 * @return the cataAudio
	 */
	public String getCataAudio() {
		return this.cataAudio;
	}
	
	/**
	 * @param cataAudio the cataAudio to set
	 */
	public void setCataAudio(String value) {
		this.cataAudio = value;
	}

	/**
	 * @return the cataDuration
	 */
	public String getCataDuration() {
		return this.cataDuration;
	}
	
	/**
	 * @param cataDuration the cataDuration to set
	 */
	public void setCataDuration(String value) {
		this.cataDuration = value;
	}

	/**
	 * @return the cataField1
	 */
	public String getCataField1() {
		return this.cataField1;
	}
	
	/**
	 * @param cataField1 the cataField1 to set
	 */
	public void setCataField1(String value) {
		this.cataField1 = value;
	}

	/**
	 * @return the cataField2
	 */
	public String getCataField2() {
		return this.cataField2;
	}
	
	/**
	 * @param cataField2 the cataField2 to set
	 */
	public void setCataField2(String value) {
		this.cataField2 = value;
	}

	/**
	 * @return the cataId
	 */
	public String getCataId() {
		return this.cataId;
	}
	
	/**
	 * @param cataId the cataId to set
	 */
	public void setCataId(String value) {
		this.cataId = value;
	}

	/**
	 * @return the cataKeywords
	 */
	public String getCataKeywords() {
		return this.cataKeywords;
	}
	
	/**
	 * @param cataKeywords the cataKeywords to set
	 */
	public void setCataKeywords(String value) {
		this.cataKeywords = value;
	}

	/**
	 * @return the cataPgmCode
	 */
	public String getCataPgmCode() {
		return this.cataPgmCode;
	}
	
	/**
	 * @param cataPgmCode the cataPgmCode to set
	 */
	public void setCataPgmCode(String value) {
		this.cataPgmCode = value;
	}

	/**
	 * @return the cataShootingPlace
	 */
	public String getCataShootingPlace() {
		return this.cataShootingPlace;
	}
	
	/**
	 * @param cataShootingPlace the cataShootingPlace to set
	 */
	public void setCataShootingPlace(String value) {
		this.cataShootingPlace = value;
	}

	/**
	 * @return the cataShootingUser
	 */
	public String getCataShootingUser() {
		return this.cataShootingUser;
	}
	
	/**
	 * @param cataShootingUser the cataShootingUser to set
	 */
	public void setCataShootingUser(String value) {
		this.cataShootingUser = value;
	}

	/**
	 * @return the cataSign
	 */
	public Integer getCataSign() {
		return this.cataSign;
	}
	
	/**
	 * @param cataSign the cataSign to set
	 */
	public void setCataSign(Integer value) {
		this.cataSign = value;
	}

	/**
	 * @return the cataTime
	 */
	public String getCataTime() {
		return this.cataTime;
	}
	
	/**
	 * @param cataTime the cataTime to set
	 */
	public void setCataTime(String value) {
		this.cataTime = value;
	}

	/**
	 * @return the cataUser
	 */
	public String getCataUser() {
		return this.cataUser;
	}
	
	/**
	 * @param cataUser the cataUser to set
	 */
	public void setCataUser(String value) {
		this.cataUser = value;
	}

	/**
	 * @return the cataVideo
	 */
	public String getCataVideo() {
		return this.cataVideo;
	}
	
	/**
	 * @param cataVideo the cataVideo to set
	 */
	public void setCataVideo(String value) {
		this.cataVideo = value;
	}

	/**
	 * @return the cataWhat
	 */
	public String getCataWhat() {
		return this.cataWhat;
	}
	
	/**
	 * @param cataWhat the cataWhat to set
	 */
	public void setCataWhat(String value) {
		this.cataWhat = value;
	}

	/**
	 * @return the cataWhen
	 */
	public Date getCataWhen() {
		return this.cataWhen;
	}
	
	/**
	 * @param cataWhen the cataWhen to set
	 */
	public void setCataWhen(Date value) {
		this.cataWhen = value;
	}

	/**
	 * @return the cataWhere
	 */
	public String getCataWhere() {
		return this.cataWhere;
	}
	
	/**
	 * @param cataWhere the cataWhere to set
	 */
	public void setCataWhere(String value) {
		this.cataWhere = value;
	}

	/**
	 * @return the cataWho
	 */
	public String getCataWho() {
		return this.cataWho;
	}
	
	/**
	 * @param cataWho the cataWho to set
	 */
	public void setCataWho(String value) {
		this.cataWho = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskFileCata)) {
			return false;
		}
		PpnTaskFileCata other = (PpnTaskFileCata)o;
		if (null == this.cataId) {
			if (other.cataId != null)
				return false;
		} else if (!this.cataId.equals(other.cataId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cataId == null) ? 0 : cataId.hashCode());
		return result;
	}
	
}