/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnTaskCata.java
 * 日 期：Fri Jul 29 10:10:02 CST 2016
 */
package jetsennet.jue2.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_TASK_CATA", keyGenerator = "uuid")
public class PpnTaskCata implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CLIP_CATA_AUDIO = "CLIP_CATA_AUDIO";
	public static String PROP_CLIP_CATA_CONTENT_DESC = "CLIP_CATA_CONTENT_DESC";
	public static String PROP_CLIP_CATA_DURATION = "CLIP_CATA_DURATION";
	public static String PROP_CLIP_CATA_FIELD1 = "CLIP_CATA_FIELD1";
	public static String PROP_CLIP_CATA_FIELD2 = "CLIP_CATA_FIELD2";
	public static String PROP_CLIP_CATA_ID = "CLIP_CATA_ID";
	public static String PROP_CLIP_CATA_PGM_CODE = "CLIP_CATA_PGM_CODE";
	public static String PROP_CLIP_CATA_SHOOTING_PLACE = "CLIP_CATA_SHOOTING_PLACE";
	public static String PROP_CLIP_CATA_SHOOTING_USER = "CLIP_CATA_SHOOTING_USER";
	public static String PROP_CLIP_CATA_VIDEO = "CLIP_CATA_VIDEO";
	
	/** primary key field of clipCataId */
	@FieldMapping(columnName = "CLIP_CATA_ID", columnType = 12, primary = true)
	private String clipCataId;
	@FieldMapping(columnName = "CLIP_CATA_AUDIO", columnType = 12)
	private String clipCataAudio;
	@FieldMapping(columnName = "CLIP_CATA_CONTENT_DESC", columnType = 12)
	private String clipCataContentDesc;
	@FieldMapping(columnName = "CLIP_CATA_DURATION", columnType = 12)
	private String clipCataDuration;
	@FieldMapping(columnName = "CLIP_CATA_FIELD1", columnType = 12)
	private String clipCataField1;
	@FieldMapping(columnName = "CLIP_CATA_FIELD2", columnType = 12)
	private String clipCataField2;
	@FieldMapping(columnName = "CLIP_CATA_PGM_CODE", columnType = 12)
	private String clipCataPgmCode;
	@FieldMapping(columnName = "CLIP_CATA_SHOOTING_PLACE", columnType = 12)
	private String clipCataShootingPlace;
	@FieldMapping(columnName = "CLIP_CATA_SHOOTING_USER", columnType = 12)
	private String clipCataShootingUser;
	@FieldMapping(columnName = "CLIP_CATA_VIDEO", columnType = 12)
	private String clipCataVideo;
	
	public PpnTaskCata() {
		super();
	}

	public PpnTaskCata(String clipCataId) {
		this.clipCataId = clipCataId;
	}

	/**
	 * @return the clipCataAudio
	 */
	public String getClipCataAudio() {
		return this.clipCataAudio;
	}
	
	/**
	 * @param clipCataAudio the clipCataAudio to set
	 */
	public void setClipCataAudio(String value) {
		this.clipCataAudio = value;
	}

	/**
	 * @return the clipCataContentDesc
	 */
	public String getClipCataContentDesc() {
		return this.clipCataContentDesc;
	}
	
	/**
	 * @param clipCataContentDesc the clipCataContentDesc to set
	 */
	public void setClipCataContentDesc(String value) {
		this.clipCataContentDesc = value;
	}

	/**
	 * @return the clipCataDuration
	 */
	public String getClipCataDuration() {
		return this.clipCataDuration;
	}
	
	/**
	 * @param clipCataDuration the clipCataDuration to set
	 */
	public void setClipCataDuration(String value) {
		this.clipCataDuration = value;
	}

	/**
	 * @return the clipCataField1
	 */
	public String getClipCataField1() {
		return this.clipCataField1;
	}
	
	/**
	 * @param clipCataField1 the clipCataField1 to set
	 */
	public void setClipCataField1(String value) {
		this.clipCataField1 = value;
	}

	/**
	 * @return the clipCataField2
	 */
	public String getClipCataField2() {
		return this.clipCataField2;
	}
	
	/**
	 * @param clipCataField2 the clipCataField2 to set
	 */
	public void setClipCataField2(String value) {
		this.clipCataField2 = value;
	}

	/**
	 * @return the clipCataId
	 */
	public String getClipCataId() {
		return this.clipCataId;
	}
	
	/**
	 * @param clipCataId the clipCataId to set
	 */
	public void setClipCataId(String value) {
		this.clipCataId = value;
	}

	/**
	 * @return the clipCataPgmCode
	 */
	public String getClipCataPgmCode() {
		return this.clipCataPgmCode;
	}
	
	/**
	 * @param clipCataPgmCode the clipCataPgmCode to set
	 */
	public void setClipCataPgmCode(String value) {
		this.clipCataPgmCode = value;
	}

	/**
	 * @return the clipCataShootingPlace
	 */
	public String getClipCataShootingPlace() {
		return this.clipCataShootingPlace;
	}
	
	/**
	 * @param clipCataShootingPlace the clipCataShootingPlace to set
	 */
	public void setClipCataShootingPlace(String value) {
		this.clipCataShootingPlace = value;
	}

	/**
	 * @return the clipCataShootingUser
	 */
	public String getClipCataShootingUser() {
		return this.clipCataShootingUser;
	}
	
	/**
	 * @param clipCataShootingUser the clipCataShootingUser to set
	 */
	public void setClipCataShootingUser(String value) {
		this.clipCataShootingUser = value;
	}

	/**
	 * @return the clipCataVideo
	 */
	public String getClipCataVideo() {
		return this.clipCataVideo;
	}
	
	/**
	 * @param clipCataVideo the clipCataVideo to set
	 */
	public void setClipCataVideo(String value) {
		this.clipCataVideo = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnTaskCata)) {
			return false;
		}
		PpnTaskCata other = (PpnTaskCata)o;
		if (null == this.clipCataId) {
			if (other.clipCataId != null)
				return false;
		} else if (!this.clipCataId.equals(other.clipCataId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clipCataId == null) ? 0 : clipCataId.hashCode());
		return result;
	}
	
}