/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentObj2Rack.java
 * 日 期：Mon Nov 28 16:10:28 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_OBJ_2_RACK", keyGenerator = "uuid")
public class PpnRentObj2Rack implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_O2R_ID = "O2R_ID";
	public static String PROP_OBJ_ID = "OBJ_ID";
	public static String PROP_SKU_ID = "SKU_ID";
	
	/** primary key field of o2rId */
	@FieldMapping(columnName = "O2R_ID", columnType = 12, primary = true)
	private String o2rId;
	@FieldMapping(columnName = "OBJ_ID", columnType = 12)
	private String objId;
	@FieldMapping(columnName = "SKU_ID", columnType = 12)
	private String skuId;
	
	public PpnRentObj2Rack() {
		super();
	}

	public PpnRentObj2Rack(String o2rId) {
		this.o2rId = o2rId;
	}

	/**
	 * @return the o2rId
	 */
	public String getO2rId() {
		return this.o2rId;
	}
	
	/**
	 * @param o2rId the o2rId to set
	 */
	public void setO2rId(String value) {
		this.o2rId = value;
	}

	/**
	 * @return the objId
	 */
	public String getObjId() {
		return this.objId;
	}
	
	/**
	 * @param objId the objId to set
	 */
	public void setObjId(String value) {
		this.objId = value;
	}

	/**
	 * @return the skuId
	 */
	public String getSkuId() {
		return this.skuId;
	}
	
	/**
	 * @param skuId the skuId to set
	 */
	public void setSkuId(String value) {
		this.skuId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentObj2Rack)) {
			return false;
		}
		PpnRentObj2Rack other = (PpnRentObj2Rack)o;
		if (null == this.o2rId) {
			if (other.o2rId != null)
				return false;
		} else if (!this.o2rId.equals(other.o2rId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((o2rId == null) ? 0 : o2rId.hashCode());
		return result;
	}
	
}