/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentRack.java
 * 日 期：Mon Nov 28 16:10:29 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_RACK", keyGenerator = "uuid")
public class PpnRentRack implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_RACK_CODE = "RACK_CODE";
	public static String PROP_RACK_COLUMN_SUM = "RACK_COLUMN_SUM";
	public static String PROP_RACK_CREATE_TIME = "RACK_CREATE_TIME";
	public static String PROP_RACK_DESC = "RACK_DESC";
	public static String PROP_RACK_FILED1 = "RACK_FILED1";
	public static String PROP_RACK_FILED2 = "RACK_FILED2";
	public static String PROP_RACK_HIGHTH = "RACK_HIGHTH";
	public static String PROP_RACK_ID = "RACK_ID";
	public static String PROP_RACK_LENGTH = "RACK_LENGTH";
	public static String PROP_RACK_NAME = "RACK_NAME";
	public static String PROP_RACK_ROW_SUM = "RACK_ROW_SUM";
	public static String PROP_RACK_STATUS = "RACK_STATUS";
	public static String PROP_RACK_TYPE = "RACK_TYPE";
	public static String PROP_RACK_WIDTH = "RACK_WIDTH";
	public static String PROP_ROOM_ID = "ROOM_ID";
	
	/** primary key field of rackId */
	@FieldMapping(columnName = "RACK_ID", columnType = 12, primary = true)
	private String rackId;
	@FieldMapping(columnName = "RACK_CODE", columnType = 12)
	private String rackCode;
	@FieldMapping(columnName = "RACK_COLUMN_SUM", columnType = 2)
	private Integer rackColumnSum;
	@FieldMapping(columnName = "RACK_CREATE_TIME", columnType = 93)
	private Date rackCreateTime;
	@FieldMapping(columnName = "RACK_DESC", columnType = 12)
	private String rackDesc;
	@FieldMapping(columnName = "RACK_FILED1", columnType = 12)
	private String rackFiled1;
	@FieldMapping(columnName = "RACK_FILED2", columnType = 12)
	private String rackFiled2;
	@FieldMapping(columnName = "RACK_HIGHTH", columnType = 2)
	private Integer rackHighth;
	@FieldMapping(columnName = "RACK_LENGTH", columnType = 2)
	private Integer rackLength;
	@FieldMapping(columnName = "RACK_NAME", columnType = 12)
	private String rackName;
	@FieldMapping(columnName = "RACK_ROW_SUM", columnType = 2)
	private Integer rackRowSum;
	@FieldMapping(columnName = "RACK_STATUS", columnType = 2)
	private Integer rackStatus;
	@FieldMapping(columnName = "RACK_TYPE", columnType = 2)
	private Integer rackType;
	@FieldMapping(columnName = "RACK_WIDTH", columnType = 2)
	private Integer rackWidth;
	@FieldMapping(columnName = "ROOM_ID", columnType = 12)
	private String roomId;
	
	public PpnRentRack() {
		super();
	}

	public PpnRentRack(String rackId) {
		this.rackId = rackId;
	}

	public PpnRentRack(String rackCode, String rackName) {
		this.rackCode = rackCode;
		this.rackName = rackName;
	}

	/**
	 * @return the rackCode
	 */
	public String getRackCode() {
		return this.rackCode;
	}
	
	/**
	 * @param rackCode the rackCode to set
	 */
	public void setRackCode(String value) {
		this.rackCode = value;
	}

	/**
	 * @return the rackColumnSum
	 */
	public Integer getRackColumnSum() {
		return this.rackColumnSum;
	}
	
	/**
	 * @param rackColumnSum the rackColumnSum to set
	 */
	public void setRackColumnSum(Integer value) {
		this.rackColumnSum = value;
	}

	/**
	 * @return the rackCreateTime
	 */
	public Date getRackCreateTime() {
		return this.rackCreateTime;
	}
	
	/**
	 * @param rackCreateTime the rackCreateTime to set
	 */
	public void setRackCreateTime(Date value) {
		this.rackCreateTime = value;
	}

	/**
	 * @return the rackDesc
	 */
	public String getRackDesc() {
		return this.rackDesc;
	}
	
	/**
	 * @param rackDesc the rackDesc to set
	 */
	public void setRackDesc(String value) {
		this.rackDesc = value;
	}

	/**
	 * @return the rackFiled1
	 */
	public String getRackFiled1() {
		return this.rackFiled1;
	}
	
	/**
	 * @param rackFiled1 the rackFiled1 to set
	 */
	public void setRackFiled1(String value) {
		this.rackFiled1 = value;
	}

	/**
	 * @return the rackFiled2
	 */
	public String getRackFiled2() {
		return this.rackFiled2;
	}
	
	/**
	 * @param rackFiled2 the rackFiled2 to set
	 */
	public void setRackFiled2(String value) {
		this.rackFiled2 = value;
	}

	/**
	 * @return the rackHighth
	 */
	public Integer getRackHighth() {
		return this.rackHighth;
	}
	
	/**
	 * @param rackHighth the rackHighth to set
	 */
	public void setRackHighth(Integer value) {
		this.rackHighth = value;
	}

	/**
	 * @return the rackId
	 */
	public String getRackId() {
		return this.rackId;
	}
	
	/**
	 * @param rackId the rackId to set
	 */
	public void setRackId(String value) {
		this.rackId = value;
	}

	/**
	 * @return the rackLength
	 */
	public Integer getRackLength() {
		return this.rackLength;
	}
	
	/**
	 * @param rackLength the rackLength to set
	 */
	public void setRackLength(Integer value) {
		this.rackLength = value;
	}

	/**
	 * @return the rackName
	 */
	public String getRackName() {
		return this.rackName;
	}
	
	/**
	 * @param rackName the rackName to set
	 */
	public void setRackName(String value) {
		this.rackName = value;
	}

	/**
	 * @return the rackRowSum
	 */
	public Integer getRackRowSum() {
		return this.rackRowSum;
	}
	
	/**
	 * @param rackRowSum the rackRowSum to set
	 */
	public void setRackRowSum(Integer value) {
		this.rackRowSum = value;
	}

	/**
	 * @return the rackStatus
	 */
	public Integer getRackStatus() {
		return this.rackStatus;
	}
	
	/**
	 * @param rackStatus the rackStatus to set
	 */
	public void setRackStatus(Integer value) {
		this.rackStatus = value;
	}

	/**
	 * @return the rackType
	 */
	public Integer getRackType() {
		return this.rackType;
	}
	
	/**
	 * @param rackType the rackType to set
	 */
	public void setRackType(Integer value) {
		this.rackType = value;
	}

	/**
	 * @return the rackWidth
	 */
	public Integer getRackWidth() {
		return this.rackWidth;
	}
	
	/**
	 * @param rackWidth the rackWidth to set
	 */
	public void setRackWidth(Integer value) {
		this.rackWidth = value;
	}

	/**
	 * @return the roomId
	 */
	public String getRoomId() {
		return this.roomId;
	}
	
	/**
	 * @param roomId the roomId to set
	 */
	public void setRoomId(String value) {
		this.roomId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentRack)) {
			return false;
		}
		PpnRentRack other = (PpnRentRack)o;
		if (null == this.rackId) {
			if (other.rackId != null)
				return false;
		} else if (!this.rackId.equals(other.rackId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rackId == null) ? 0 : rackId.hashCode());
		return result;
	}
	
}