/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentRackSku.java
 * 日 期：Thu Nov 10 10:15:06 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_RACK_SKU", keyGenerator = "uuid")
public class PpnRentRackSku implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_RACK_ID = "RACK_ID";
	public static String PROP_SKU_CODE = "SKU_CODE";
	public static String PROP_SKU_COLUMN_INDEX = "SKU_COLUMN_INDEX";
	public static String PROP_SKU_DESC = "SKU_DESC";
	public static String PROP_SKU_FIELD1 = "SKU_FIELD1";
	public static String PROP_SKU_FIELD2 = "SKU_FIELD2";
	public static String PROP_SKU_HIGHTH = "SKU_HIGHTH";
	public static String PROP_SKU_ID = "SKU_ID";
	public static String PROP_SKU_LENGTH = "SKU_LENGTH";
	public static String PROP_SKU_NAME = "SKU_NAME";
	public static String PROP_SKU_ROW_INDEX = "SKU_ROW_INDEX";
	public static String PROP_SKU_STATUS = "SKU_STATUS";
	public static String PROP_SKU_WIDTH = "SKU_WIDTH";
	
	/** primary key field of skuId */
	@FieldMapping(columnName = "SKU_ID", columnType = 12, primary = true)
	private String skuId;
	@FieldMapping(columnName = "RACK_ID", columnType = 12)
	private String rackId;
	@FieldMapping(columnName = "SKU_CODE", columnType = 12)
	private String skuCode;
	@FieldMapping(columnName = "SKU_COLUMN_INDEX", columnType = 2)
	private Integer skuColumnIndex;
	@FieldMapping(columnName = "SKU_DESC", columnType = 12)
	private String skuDesc;
	@FieldMapping(columnName = "SKU_FIELD1", columnType = 12)
	private String skuField1;
	@FieldMapping(columnName = "SKU_FIELD2", columnType = 12)
	private String skuField2;
	@FieldMapping(columnName = "SKU_HIGHTH", columnType = 2)
	private Integer skuHighth;
	@FieldMapping(columnName = "SKU_LENGTH", columnType = 2)
	private Integer skuLength;
	@FieldMapping(columnName = "SKU_NAME", columnType = 12)
	private String skuName;
	@FieldMapping(columnName = "SKU_ROW_INDEX", columnType = 2)
	private Integer skuRowIndex;
	@FieldMapping(columnName = "SKU_STATUS", columnType = 2)
	private Integer skuStatus;
	@FieldMapping(columnName = "SKU_WIDTH", columnType = 2)
	private Integer skuWidth;
	
	public PpnRentRackSku() {
		super();
	}

	public PpnRentRackSku(String skuId) {
		this.skuId = skuId;
	}

	public PpnRentRackSku(String rackId, String skuCode, String skuName) {
		this.rackId = rackId;
		this.skuCode = skuCode;
		this.skuName = skuName;
	}

	/**
	 * @return the rackId
	 */
	public String getRackId() {
		return this.rackId;
	}
	
	/**
	 * @param rackId the rackId to set
	 */
	public void setRackId(String value) {
		this.rackId = value;
	}

	/**
	 * @return the skuCode
	 */
	public String getSkuCode() {
		return this.skuCode;
	}
	
	/**
	 * @param skuCode the skuCode to set
	 */
	public void setSkuCode(String value) {
		this.skuCode = value;
	}

	/**
	 * @return the skuColumnIndex
	 */
	public Integer getSkuColumnIndex() {
		return this.skuColumnIndex;
	}
	
	/**
	 * @param skuColumnIndex the skuColumnIndex to set
	 */
	public void setSkuColumnIndex(Integer value) {
		this.skuColumnIndex = value;
	}

	/**
	 * @return the skuDesc
	 */
	public String getSkuDesc() {
		return this.skuDesc;
	}
	
	/**
	 * @param skuDesc the skuDesc to set
	 */
	public void setSkuDesc(String value) {
		this.skuDesc = value;
	}

	/**
	 * @return the skuField1
	 */
	public String getSkuField1() {
		return this.skuField1;
	}
	
	/**
	 * @param skuField1 the skuField1 to set
	 */
	public void setSkuField1(String value) {
		this.skuField1 = value;
	}

	/**
	 * @return the skuField2
	 */
	public String getSkuField2() {
		return this.skuField2;
	}
	
	/**
	 * @param skuField2 the skuField2 to set
	 */
	public void setSkuField2(String value) {
		this.skuField2 = value;
	}

	/**
	 * @return the skuHighth
	 */
	public Integer getSkuHighth() {
		return this.skuHighth;
	}
	
	/**
	 * @param skuHighth the skuHighth to set
	 */
	public void setSkuHighth(Integer value) {
		this.skuHighth = value;
	}

	/**
	 * @return the skuId
	 */
	public String getSkuId() {
		return this.skuId;
	}
	
	/**
	 * @param skuId the skuId to set
	 */
	public void setSkuId(String value) {
		this.skuId = value;
	}

	/**
	 * @return the skuLength
	 */
	public Integer getSkuLength() {
		return this.skuLength;
	}
	
	/**
	 * @param skuLength the skuLength to set
	 */
	public void setSkuLength(Integer value) {
		this.skuLength = value;
	}

	/**
	 * @return the skuName
	 */
	public String getSkuName() {
		return this.skuName;
	}
	
	/**
	 * @param skuName the skuName to set
	 */
	public void setSkuName(String value) {
		this.skuName = value;
	}

	/**
	 * @return the skuRowIndex
	 */
	public Integer getSkuRowIndex() {
		return this.skuRowIndex;
	}
	
	/**
	 * @param skuRowIndex the skuRowIndex to set
	 */
	public void setSkuRowIndex(Integer value) {
		this.skuRowIndex = value;
	}

	/**
	 * @return the skuStatus
	 */
	public Integer getSkuStatus() {
		return this.skuStatus;
	}
	
	/**
	 * @param skuStatus the skuStatus to set
	 */
	public void setSkuStatus(Integer value) {
		this.skuStatus = value;
	}

	/**
	 * @return the skuWidth
	 */
	public Integer getSkuWidth() {
		return this.skuWidth;
	}
	
	/**
	 * @param skuWidth the skuWidth to set
	 */
	public void setSkuWidth(Integer value) {
		this.skuWidth = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentRackSku)) {
			return false;
		}
		PpnRentRackSku other = (PpnRentRackSku)o;
		if (null == this.skuId) {
			if (other.skuId != null)
				return false;
		} else if (!this.skuId.equals(other.skuId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((skuId == null) ? 0 : skuId.hashCode());
		return result;
	}
	
}