/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentOrdItem.java
 * 日 期：Tue Dec 20 19:35:20 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_ORD_ITEM", keyGenerator = "uuid")
public class PpnRentOrdItem implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ITEM_CODE = "ITEM_CODE";
	public static String PROP_ITEM_CREATE_TIME = "ITEM_CREATE_TIME";
	public static String PROP_ITEM_END_TIME = "ITEM_END_TIME";
	public static String PROP_ITEM_FIELD1 = "ITEM_FIELD1";
	public static String PROP_ITEM_FIELD2 = "ITEM_FIELD2";
	public static String PROP_ITEM_ID = "ITEM_ID";
	public static String PROP_ITEM_NAME = "ITEM_NAME";
	public static String PROP_ITEM_OBJ_CODE = "ITEM_OBJ_CODE";
	public static String PROP_ITEM_OBJ_CURRENCY = "ITEM_OBJ_CURRENCY";
	public static String PROP_ITEM_OBJ_DESC = "ITEM_OBJ_DESC";
	public static String PROP_ITEM_OBJ_KEY = "ITEM_OBJ_KEY";
	public static String PROP_ITEM_OBJ_NUM = "ITEM_OBJ_NUM";
	public static String PROP_ITEM_OBJ_PRICE = "ITEM_OBJ_PRICE";
	public static String PROP_ITEM_OBJ_SPECS = "ITEM_OBJ_SPECS";
	public static String PROP_ITEM_OBJ_TYPE = "ITEM_OBJ_TYPE";
	public static String PROP_ITEM_OBJ_UOM = "ITEM_OBJ_UOM";
	public static String PROP_ITEM_OBJ_UOM_SUM = "ITEM_OBJ_UOM_SUM";
	public static String PROP_ITEM_REMARK = "ITEM_REMARK";
	public static String PROP_ITEM_START_TIME = "ITEM_START_TIME";
	public static String PROP_ITEM_STATUS = "ITEM_STATUS";
	public static String PROP_ITEM_TYPE = "ITEM_TYPE";
	public static String PROP_ORD_ID = "ORD_ID";
	
	/** primary key field of itemId */
	@FieldMapping(columnName = "ITEM_ID", columnType = 12, primary = true)
	private String itemId;
	@FieldMapping(columnName = "ITEM_CODE", columnType = 12)
	private String itemCode;
	@FieldMapping(columnName = "ITEM_CREATE_TIME", columnType = 93)
	private Date itemCreateTime;
	@FieldMapping(columnName = "ITEM_END_TIME", columnType = 93)
	private Date itemEndTime;
	@FieldMapping(columnName = "ITEM_FIELD1", columnType = 12)
	private String itemField1;
	@FieldMapping(columnName = "ITEM_FIELD2", columnType = 12)
	private String itemField2;
	@FieldMapping(columnName = "ITEM_NAME", columnType = 12)
	private String itemName;
	@FieldMapping(columnName = "ITEM_OBJ_CODE", columnType = 12)
	private String itemObjCode;
	@FieldMapping(columnName = "ITEM_OBJ_CURRENCY", columnType = 12)
	private String itemObjCurrency;
	@FieldMapping(columnName = "ITEM_OBJ_DESC", columnType = 12)
	private String itemObjDesc;
	@FieldMapping(columnName = "ITEM_OBJ_KEY", columnType = 12)
	private String itemObjKey;
	@FieldMapping(columnName = "ITEM_OBJ_NUM", columnType = 2)
	private Integer itemObjNum;
	@FieldMapping(columnName = "ITEM_OBJ_PRICE", columnType = 2)
	private Integer itemObjPrice;
	@FieldMapping(columnName = "ITEM_OBJ_SPECS", columnType = 12)
	private String itemObjSpecs;
	@FieldMapping(columnName = "ITEM_OBJ_TYPE", columnType = 12)
	private String itemObjType;
	@FieldMapping(columnName = "ITEM_OBJ_UOM", columnType = 12)
	private String itemObjUom;
	@FieldMapping(columnName = "ITEM_OBJ_UOM_SUM", columnType = 2)
	private Integer itemObjUomSum;
	@FieldMapping(columnName = "ITEM_REMARK", columnType = 12)
	private String itemRemark;
	@FieldMapping(columnName = "ITEM_START_TIME", columnType = 93)
	private Date itemStartTime;
	@FieldMapping(columnName = "ITEM_STATUS", columnType = 2)
	private Integer itemStatus;
	@FieldMapping(columnName = "ITEM_TYPE", columnType = 2)
	private Integer itemType;
	@FieldMapping(columnName = "ORD_ID", columnType = 12)
	private String ordId;
	
	public PpnRentOrdItem() {
		super();
	}

	public PpnRentOrdItem(String itemId) {
		this.itemId = itemId;
	}

	/**
	 * @return the itemCode
	 */
	public String getItemCode() {
		return this.itemCode;
	}
	
	/**
	 * @param itemCode the itemCode to set
	 */
	public void setItemCode(String value) {
		this.itemCode = value;
	}

	/**
	 * @return the itemCreateTime
	 */
	public Date getItemCreateTime() {
		return this.itemCreateTime;
	}
	
	/**
	 * @param itemCreateTime the itemCreateTime to set
	 */
	public void setItemCreateTime(Date value) {
		this.itemCreateTime = value;
	}

	/**
	 * @return the itemEndTime
	 */
	public Date getItemEndTime() {
		return this.itemEndTime;
	}
	
	/**
	 * @param itemEndTime the itemEndTime to set
	 */
	public void setItemEndTime(Date value) {
		this.itemEndTime = value;
	}

	/**
	 * @return the itemField1
	 */
	public String getItemField1() {
		return this.itemField1;
	}
	
	/**
	 * @param itemField1 the itemField1 to set
	 */
	public void setItemField1(String value) {
		this.itemField1 = value;
	}

	/**
	 * @return the itemField2
	 */
	public String getItemField2() {
		return this.itemField2;
	}
	
	/**
	 * @param itemField2 the itemField2 to set
	 */
	public void setItemField2(String value) {
		this.itemField2 = value;
	}

	/**
	 * @return the itemId
	 */
	public String getItemId() {
		return this.itemId;
	}
	
	/**
	 * @param itemId the itemId to set
	 */
	public void setItemId(String value) {
		this.itemId = value;
	}

	/**
	 * @return the itemName
	 */
	public String getItemName() {
		return this.itemName;
	}
	
	/**
	 * @param itemName the itemName to set
	 */
	public void setItemName(String value) {
		this.itemName = value;
	}

	/**
	 * @return the itemObjCode
	 */
	public String getItemObjCode() {
		return this.itemObjCode;
	}
	
	/**
	 * @param itemObjCode the itemObjCode to set
	 */
	public void setItemObjCode(String value) {
		this.itemObjCode = value;
	}

	/**
	 * @return the itemObjCurrency
	 */
	public String getItemObjCurrency() {
		return this.itemObjCurrency;
	}
	
	/**
	 * @param itemObjCurrency the itemObjCurrency to set
	 */
	public void setItemObjCurrency(String value) {
		this.itemObjCurrency = value;
	}

	/**
	 * @return the itemObjDesc
	 */
	public String getItemObjDesc() {
		return this.itemObjDesc;
	}
	
	/**
	 * @param itemObjDesc the itemObjDesc to set
	 */
	public void setItemObjDesc(String value) {
		this.itemObjDesc = value;
	}

	/**
	 * @return the itemObjKey
	 */
	public String getItemObjKey() {
		return this.itemObjKey;
	}
	
	/**
	 * @param itemObjKey the itemObjKey to set
	 */
	public void setItemObjKey(String value) {
		this.itemObjKey = value;
	}

	/**
	 * @return the itemObjNum
	 */
	public Integer getItemObjNum() {
		return this.itemObjNum;
	}
	
	/**
	 * @param itemObjNum the itemObjNum to set
	 */
	public void setItemObjNum(Integer value) {
		this.itemObjNum = value;
	}

	/**
	 * @return the itemObjPrice
	 */
	public Integer getItemObjPrice() {
		return this.itemObjPrice;
	}
	
	/**
	 * @param itemObjPrice the itemObjPrice to set
	 */
	public void setItemObjPrice(Integer value) {
		this.itemObjPrice = value;
	}

	/**
	 * @return the itemObjSpecs
	 */
	public String getItemObjSpecs() {
		return this.itemObjSpecs;
	}
	
	/**
	 * @param itemObjSpecs the itemObjSpecs to set
	 */
	public void setItemObjSpecs(String value) {
		this.itemObjSpecs = value;
	}

	/**
	 * @return the itemObjType
	 */
	public String getItemObjType() {
		return this.itemObjType;
	}
	
	/**
	 * @param itemObjType the itemObjType to set
	 */
	public void setItemObjType(String value) {
		this.itemObjType = value;
	}

	/**
	 * @return the itemObjUom
	 */
	public String getItemObjUom() {
		return this.itemObjUom;
	}
	
	/**
	 * @param itemObjUom the itemObjUom to set
	 */
	public void setItemObjUom(String value) {
		this.itemObjUom = value;
	}

	/**
	 * @return the itemObjUomSum
	 */
	public Integer getItemObjUomSum() {
		return this.itemObjUomSum;
	}
	
	/**
	 * @param itemObjUomSum the itemObjUomSum to set
	 */
	public void setItemObjUomSum(Integer value) {
		this.itemObjUomSum = value;
	}

	/**
	 * @return the itemRemark
	 */
	public String getItemRemark() {
		return this.itemRemark;
	}
	
	/**
	 * @param itemRemark the itemRemark to set
	 */
	public void setItemRemark(String value) {
		this.itemRemark = value;
	}

	/**
	 * @return the itemStartTime
	 */
	public Date getItemStartTime() {
		return this.itemStartTime;
	}
	
	/**
	 * @param itemStartTime the itemStartTime to set
	 */
	public void setItemStartTime(Date value) {
		this.itemStartTime = value;
	}

	/**
	 * @return the itemStatus
	 */
	public Integer getItemStatus() {
		return this.itemStatus;
	}
	
	/**
	 * @param itemStatus the itemStatus to set
	 */
	public void setItemStatus(Integer value) {
		this.itemStatus = value;
	}

	/**
	 * @return the itemType
	 */
	public Integer getItemType() {
		return this.itemType;
	}
	
	/**
	 * @param itemType the itemType to set
	 */
	public void setItemType(Integer value) {
		this.itemType = value;
	}

	/**
	 * @return the ordId
	 */
	public String getOrdId() {
		return this.ordId;
	}
	
	/**
	 * @param ordId the ordId to set
	 */
	public void setOrdId(String value) {
		this.ordId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentOrdItem)) {
			return false;
		}
		PpnRentOrdItem other = (PpnRentOrdItem)o;
		if (null == this.itemId) {
			if (other.itemId != null)
				return false;
		} else if (!this.itemId.equals(other.itemId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}
	
}