/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentComponent.java
 * 日 期：Thu Jan 05 13:18:58 CST 2017
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_COMPONENT", keyGenerator = "uuid")
public class PpnRentComponent implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_COMP_ALIVE_NUM = "COMP_ALIVE_NUM";
	public static String PROP_COMP_CODE = "COMP_CODE";
	public static String PROP_COMP_CREATE_TIME = "COMP_CREATE_TIME";
	public static String PROP_COMP_DESC = "COMP_DESC";
	public static String PROP_COMP_FIELD1 = "COMP_FIELD1";
	public static String PROP_COMP_ID = "COMP_ID";
	public static String PROP_COMP_NAME = "COMP_NAME";
	public static String PROP_COMP_TOTAL_NUM = "COMP_TOTAL_NUM";
	public static String PROP_COMP_TYPE = "COMP_TYPE";
	
	/** primary key field of compId */
	@FieldMapping(columnName = "COMP_ID", columnType = 12, primary = true)
	private String compId;
	@FieldMapping(columnName = "COMP_ALIVE_NUM", columnType = 2)
	private Integer compAliveNum;
	@FieldMapping(columnName = "COMP_CODE", columnType = 12)
	private String compCode;
	@FieldMapping(columnName = "COMP_CREATE_TIME", columnType = 93)
	private Date compCreateTime;
	@FieldMapping(columnName = "COMP_DESC", columnType = 12)
	private String compDesc;
	@FieldMapping(columnName = "COMP_FIELD1", columnType = 12)
	private String compField1;
	@FieldMapping(columnName = "COMP_NAME", columnType = 12)
	private String compName;
	@FieldMapping(columnName = "COMP_TOTAL_NUM", columnType = 2)
	private Integer compTotalNum;
	@FieldMapping(columnName = "COMP_TYPE", columnType = 2)
	private Integer compType;
	
	public PpnRentComponent() {
		super();
	}

	public PpnRentComponent(String compId) {
		this.compId = compId;
	}

	public PpnRentComponent(Integer compAliveNum, String compCode, String compName, Integer compTotalNum, Integer compType) {
		this.compAliveNum = compAliveNum;
		this.compCode = compCode;
		this.compName = compName;
		this.compTotalNum = compTotalNum;
		this.compType = compType;
	}

	/**
	 * @return the compAliveNum
	 */
	public Integer getCompAliveNum() {
		return this.compAliveNum;
	}
	
	/**
	 * @param compAliveNum the compAliveNum to set
	 */
	public void setCompAliveNum(Integer value) {
		this.compAliveNum = value;
	}

	/**
	 * @return the compCode
	 */
	public String getCompCode() {
		return this.compCode;
	}
	
	/**
	 * @param compCode the compCode to set
	 */
	public void setCompCode(String value) {
		this.compCode = value;
	}

	/**
	 * @return the compCreateTime
	 */
	public Date getCompCreateTime() {
		return this.compCreateTime;
	}
	
	/**
	 * @param compCreateTime the compCreateTime to set
	 */
	public void setCompCreateTime(Date value) {
		this.compCreateTime = value;
	}

	/**
	 * @return the compDesc
	 */
	public String getCompDesc() {
		return this.compDesc;
	}
	
	/**
	 * @param compDesc the compDesc to set
	 */
	public void setCompDesc(String value) {
		this.compDesc = value;
	}

	/**
	 * @return the compField1
	 */
	public String getCompField1() {
		return this.compField1;
	}
	
	/**
	 * @param compField1 the compField1 to set
	 */
	public void setCompField1(String value) {
		this.compField1 = value;
	}

	/**
	 * @return the compId
	 */
	public String getCompId() {
		return this.compId;
	}
	
	/**
	 * @param compId the compId to set
	 */
	public void setCompId(String value) {
		this.compId = value;
	}

	/**
	 * @return the compName
	 */
	public String getCompName() {
		return this.compName;
	}
	
	/**
	 * @param compName the compName to set
	 */
	public void setCompName(String value) {
		this.compName = value;
	}

	/**
	 * @return the compTotalNum
	 */
	public Integer getCompTotalNum() {
		return this.compTotalNum;
	}
	
	/**
	 * @param compTotalNum the compTotalNum to set
	 */
	public void setCompTotalNum(Integer value) {
		this.compTotalNum = value;
	}

	/**
	 * @return the compType
	 */
	public Integer getCompType() {
		return this.compType;
	}
	
	/**
	 * @param compType the compType to set
	 */
	public void setCompType(Integer value) {
		this.compType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentComponent)) {
			return false;
		}
		PpnRentComponent other = (PpnRentComponent)o;
		if (null == this.compId) {
			if (other.compId != null)
				return false;
		} else if (!this.compId.equals(other.compId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((compId == null) ? 0 : compId.hashCode());
		return result;
	}
	
}