/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentMonTask.java
 * 日 期：Mon Dec 26 18:11:27 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_MON_TASK", keyGenerator = "uuid")
public class PpnRentMonTask implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_OBJ_ID = "OBJ_ID";
	public static String PROP_TASK_CODE = "TASK_CODE";
	public static String PROP_TASK_CREATE_TIME = "TASK_CREATE_TIME";
	public static String PROP_TASK_CREATE_USER = "TASK_CREATE_USER";
	public static String PROP_TASK_DESC = "TASK_DESC";
	public static String PROP_TASK_EXPIRE_TIME = "TASK_EXPIRE_TIME";
	public static String PROP_TASK_FIELD1 = "TASK_FIELD1";
	public static String PROP_TASK_FIELD2 = "TASK_FIELD2";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_NAME = "TASK_NAME";
	public static String PROP_TASK_PRIORITY = "TASK_PRIORITY";
	public static String PROP_TASK_REMARK = "TASK_REMARK";
	public static String PROP_TASK_STATUS = "TASK_STATUS";
	public static String PROP_TASK_TYPE = "TASK_TYPE";
	
	/** primary key field of taskId */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	/** foreign key field of PPN_RENT_OBJ.OBJ_ID */
	@FieldMapping(columnName = "OBJ_ID", columnType = 12)
	private String objId;
	@FieldMapping(columnName = "TASK_CODE", columnType = 12)
	private String taskCode;
	@FieldMapping(columnName = "TASK_CREATE_TIME", columnType = 12)
	private String taskCreateTime;
	@FieldMapping(columnName = "TASK_CREATE_USER", columnType = 12)
	private String taskCreateUser;
	@FieldMapping(columnName = "TASK_DESC", columnType = 12)
	private String taskDesc;
	@FieldMapping(columnName = "TASK_EXPIRE_TIME", columnType = 93)
	private Date taskExpireTime;
	@FieldMapping(columnName = "TASK_FIELD1", columnType = 12)
	private String taskField1;
	@FieldMapping(columnName = "TASK_FIELD2", columnType = 12)
	private String taskField2;
	@FieldMapping(columnName = "TASK_NAME", columnType = 12)
	private String taskName;
	@FieldMapping(columnName = "TASK_PRIORITY", columnType = 2)
	private Integer taskPriority;
	@FieldMapping(columnName = "TASK_REMARK", columnType = 12)
	private String taskRemark;
	@FieldMapping(columnName = "TASK_STATUS", columnType = 2)
	private Integer taskStatus;
	@FieldMapping(columnName = "TASK_TYPE", columnType = 2)
	private Integer taskType;
	
	public PpnRentMonTask() {
		super();
	}

	public PpnRentMonTask(String taskId) {
		this.taskId = taskId;
	}

	public PpnRentMonTask(String taskCode, String taskCreateTime, String taskCreateUser, String taskName, Integer taskStatus, Integer taskType) {
		this.taskCode = taskCode;
		this.taskCreateTime = taskCreateTime;
		this.taskCreateUser = taskCreateUser;
		this.taskName = taskName;
		this.taskStatus = taskStatus;
		this.taskType = taskType;
	}

	/**
	 * @return the objId
	 */
	public String getObjId() {
		return this.objId;
	}
	
	/**
	 * @param objId the objId to set
	 */
	public void setObjId(String value) {
		this.objId = value;
	}

	/**
	 * @return the taskCode
	 */
	public String getTaskCode() {
		return this.taskCode;
	}
	
	/**
	 * @param taskCode the taskCode to set
	 */
	public void setTaskCode(String value) {
		this.taskCode = value;
	}

	/**
	 * @return the taskCreateTime
	 */
	public String getTaskCreateTime() {
		return this.taskCreateTime;
	}
	
	/**
	 * @param taskCreateTime the taskCreateTime to set
	 */
	public void setTaskCreateTime(String value) {
		this.taskCreateTime = value;
	}

	/**
	 * @return the taskCreateUser
	 */
	public String getTaskCreateUser() {
		return this.taskCreateUser;
	}
	
	/**
	 * @param taskCreateUser the taskCreateUser to set
	 */
	public void setTaskCreateUser(String value) {
		this.taskCreateUser = value;
	}

	/**
	 * @return the taskDesc
	 */
	public String getTaskDesc() {
		return this.taskDesc;
	}
	
	/**
	 * @param taskDesc the taskDesc to set
	 */
	public void setTaskDesc(String value) {
		this.taskDesc = value;
	}

	/**
	 * @return the taskExpireTime
	 */
	public Date getTaskExpireTime() {
		return this.taskExpireTime;
	}
	
	/**
	 * @param taskExpireTime the taskExpireTime to set
	 */
	public void setTaskExpireTime(Date value) {
		this.taskExpireTime = value;
	}

	/**
	 * @return the taskField1
	 */
	public String getTaskField1() {
		return this.taskField1;
	}
	
	/**
	 * @param taskField1 the taskField1 to set
	 */
	public void setTaskField1(String value) {
		this.taskField1 = value;
	}

	/**
	 * @return the taskField2
	 */
	public String getTaskField2() {
		return this.taskField2;
	}
	
	/**
	 * @param taskField2 the taskField2 to set
	 */
	public void setTaskField2(String value) {
		this.taskField2 = value;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return this.taskName;
	}
	
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String value) {
		this.taskName = value;
	}

	/**
	 * @return the taskPriority
	 */
	public Integer getTaskPriority() {
		return this.taskPriority;
	}
	
	/**
	 * @param taskPriority the taskPriority to set
	 */
	public void setTaskPriority(Integer value) {
		this.taskPriority = value;
	}

	/**
	 * @return the taskRemark
	 */
	public String getTaskRemark() {
		return this.taskRemark;
	}
	
	/**
	 * @param taskRemark the taskRemark to set
	 */
	public void setTaskRemark(String value) {
		this.taskRemark = value;
	}

	/**
	 * @return the taskStatus
	 */
	public Integer getTaskStatus() {
		return this.taskStatus;
	}
	
	/**
	 * @param taskStatus the taskStatus to set
	 */
	public void setTaskStatus(Integer value) {
		this.taskStatus = value;
	}

	/**
	 * @return the taskType
	 */
	public Integer getTaskType() {
		return this.taskType;
	}
	
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(Integer value) {
		this.taskType = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentMonTask)) {
			return false;
		}
		PpnRentMonTask other = (PpnRentMonTask)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}