/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdlm.beans.PpnRentOutItem.java
 * 日 期：Thu Dec 29 19:56:17 CST 2016
 */
package jetsennet.jdlm.beans;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_RENT_OUT_ITEM", keyGenerator = "uuid")
public class PpnRentOutItem implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ITEM_CODE = "ITEM_CODE";
	public static String PROP_ITEM_FIELD1 = "ITEM_FIELD1";
	public static String PROP_ITEM_FIELD2 = "ITEM_FIELD2";
	public static String PROP_ITEM_FOLLOW_PERSON = "ITEM_FOLLOW_PERSON";
	public static String PROP_ITEM_ID = "ITEM_ID";
	public static String PROP_ITEM_MATH_CODE = "ITEM_MATH_CODE";
	public static String PROP_ITEM_NAME = "ITEM_NAME";
	public static String PROP_ITEM_OBJ_CODE = "ITEM_OBJ_CODE";
	public static String PROP_ITEM_OBJ_CURRENCY = "ITEM_OBJ_CURRENCY";
	public static String PROP_ITEM_OBJ_DESC = "ITEM_OBJ_DESC";
	public static String PROP_ITEM_OBJ_NAME = "ITEM_OBJ_NAME";
	public static String PROP_ITEM_OBJ_NUM = "ITEM_OBJ_NUM";
	public static String PROP_ITEM_OBJ_PRICE = "ITEM_OBJ_PRICE";
	public static String PROP_ITEM_OBJ_SPECS = "ITEM_OBJ_SPECS";
	public static String PROP_ITEM_OBJ_TYPE = "ITEM_OBJ_TYPE";
	public static String PROP_ITEM_OBJ_UOM = "ITEM_OBJ_UOM";
	public static String PROP_ITEM_OBJ_UOM_SUM = "ITEM_OBJ_UOM_SUM";
	public static String PROP_ITEM_REMARK = "ITEM_REMARK";
	public static String PROP_ITEM_STATUS = "ITEM_STATUS";
	public static String PROP_ITEM_TYPE = "ITEM_TYPE";
	public static String PROP_OUT_ID = "OUT_ID";
	
	/** primary key field of itemId */
	@FieldMapping(columnName = "ITEM_ID", columnType = 12, primary = true)
	private String itemId;
	@FieldMapping(columnName = "ITEM_CODE", columnType = 12)
	private String itemCode;
	@FieldMapping(columnName = "ITEM_FIELD1", columnType = 12)
	private String itemField1;
	@FieldMapping(columnName = "ITEM_FIELD2", columnType = 12)
	private String itemField2;
	@FieldMapping(columnName = "ITEM_FOLLOW_PERSON", columnType = 12)
	private String itemFollowPerson;
	@FieldMapping(columnName = "ITEM_MATH_CODE", columnType = 12)
	private String itemMathCode;
	@FieldMapping(columnName = "ITEM_NAME", columnType = 12)
	private String itemName;
	@FieldMapping(columnName = "ITEM_OBJ_CODE", columnType = 12)
	private String itemObjCode;
	@FieldMapping(columnName = "ITEM_OBJ_CURRENCY", columnType = 12)
	private String itemObjCurrency;
	@FieldMapping(columnName = "ITEM_OBJ_DESC", columnType = 12)
	private String itemObjDesc;
	@FieldMapping(columnName = "ITEM_OBJ_NAME", columnType = 12)
	private String itemObjName;
	@FieldMapping(columnName = "ITEM_OBJ_NUM", columnType = 2)
	private Integer itemObjNum;
	@FieldMapping(columnName = "ITEM_OBJ_PRICE", columnType = 2)
	private Integer itemObjPrice;
	@FieldMapping(columnName = "ITEM_OBJ_SPECS", columnType = 12)
	private String itemObjSpecs;
	@FieldMapping(columnName = "ITEM_OBJ_TYPE", columnType = 12)
	private String itemObjType;
	@FieldMapping(columnName = "ITEM_OBJ_UOM", columnType = 12)
	private String itemObjUom;
	@FieldMapping(columnName = "ITEM_OBJ_UOM_SUM", columnType = 2)
	private Integer itemObjUomSum;
	@FieldMapping(columnName = "ITEM_REMARK", columnType = 12)
	private String itemRemark;
	@FieldMapping(columnName = "ITEM_STATUS", columnType = 2)
	private Integer itemStatus;
	@FieldMapping(columnName = "ITEM_TYPE", columnType = 2)
	private Integer itemType;
	/** foreign key field of PPN_RENT_OUT.OUT_ID */
	@FieldMapping(columnName = "OUT_ID", columnType = 12)
	private String outId;
	
	public PpnRentOutItem() {
		super();
	}

	public PpnRentOutItem(String itemId) {
		this.itemId = itemId;
	}

	public PpnRentOutItem(String itemObjType, String itemObjUom) {
		this.itemObjType = itemObjType;
		this.itemObjUom = itemObjUom;
	}

	/**
	 * @return the itemCode
	 */
	public String getItemCode() {
		return this.itemCode;
	}
	
	/**
	 * @param itemCode the itemCode to set
	 */
	public void setItemCode(String value) {
		this.itemCode = value;
	}

	/**
	 * @return the itemField1
	 */
	public String getItemField1() {
		return this.itemField1;
	}
	
	/**
	 * @param itemField1 the itemField1 to set
	 */
	public void setItemField1(String value) {
		this.itemField1 = value;
	}

	/**
	 * @return the itemField2
	 */
	public String getItemField2() {
		return this.itemField2;
	}
	
	/**
	 * @param itemField2 the itemField2 to set
	 */
	public void setItemField2(String value) {
		this.itemField2 = value;
	}

	/**
	 * @return the itemFollowPerson
	 */
	public String getItemFollowPerson() {
		return this.itemFollowPerson;
	}
	
	/**
	 * @param itemFollowPerson the itemFollowPerson to set
	 */
	public void setItemFollowPerson(String value) {
		this.itemFollowPerson = value;
	}

	/**
	 * @return the itemId
	 */
	public String getItemId() {
		return this.itemId;
	}
	
	/**
	 * @param itemId the itemId to set
	 */
	public void setItemId(String value) {
		this.itemId = value;
	}

	/**
	 * @return the itemMathCode
	 */
	public String getItemMathCode() {
		return this.itemMathCode;
	}
	
	/**
	 * @param itemMathCode the itemMathCode to set
	 */
	public void setItemMathCode(String value) {
		this.itemMathCode = value;
	}

	/**
	 * @return the itemName
	 */
	public String getItemName() {
		return this.itemName;
	}
	
	/**
	 * @param itemName the itemName to set
	 */
	public void setItemName(String value) {
		this.itemName = value;
	}

	/**
	 * @return the itemObjCode
	 */
	public String getItemObjCode() {
		return this.itemObjCode;
	}
	
	/**
	 * @param itemObjCode the itemObjCode to set
	 */
	public void setItemObjCode(String value) {
		this.itemObjCode = value;
	}

	/**
	 * @return the itemObjCurrency
	 */
	public String getItemObjCurrency() {
		return this.itemObjCurrency;
	}
	
	/**
	 * @param itemObjCurrency the itemObjCurrency to set
	 */
	public void setItemObjCurrency(String value) {
		this.itemObjCurrency = value;
	}

	/**
	 * @return the itemObjDesc
	 */
	public String getItemObjDesc() {
		return this.itemObjDesc;
	}
	
	/**
	 * @param itemObjDesc the itemObjDesc to set
	 */
	public void setItemObjDesc(String value) {
		this.itemObjDesc = value;
	}

	/**
	 * @return the itemObjName
	 */
	public String getItemObjName() {
		return this.itemObjName;
	}
	
	/**
	 * @param itemObjName the itemObjName to set
	 */
	public void setItemObjName(String value) {
		this.itemObjName = value;
	}

	/**
	 * @return the itemObjNum
	 */
	public Integer getItemObjNum() {
		return this.itemObjNum;
	}
	
	/**
	 * @param itemObjNum the itemObjNum to set
	 */
	public void setItemObjNum(Integer value) {
		this.itemObjNum = value;
	}

	/**
	 * @return the itemObjPrice
	 */
	public Integer getItemObjPrice() {
		return this.itemObjPrice;
	}
	
	/**
	 * @param itemObjPrice the itemObjPrice to set
	 */
	public void setItemObjPrice(Integer value) {
		this.itemObjPrice = value;
	}

	/**
	 * @return the itemObjSpecs
	 */
	public String getItemObjSpecs() {
		return this.itemObjSpecs;
	}
	
	/**
	 * @param itemObjSpecs the itemObjSpecs to set
	 */
	public void setItemObjSpecs(String value) {
		this.itemObjSpecs = value;
	}

	/**
	 * @return the itemObjType
	 */
	public String getItemObjType() {
		return this.itemObjType;
	}
	
	/**
	 * @param itemObjType the itemObjType to set
	 */
	public void setItemObjType(String value) {
		this.itemObjType = value;
	}

	/**
	 * @return the itemObjUom
	 */
	public String getItemObjUom() {
		return this.itemObjUom;
	}
	
	/**
	 * @param itemObjUom the itemObjUom to set
	 */
	public void setItemObjUom(String value) {
		this.itemObjUom = value;
	}

	/**
	 * @return the itemObjUomSum
	 */
	public Integer getItemObjUomSum() {
		return this.itemObjUomSum;
	}
	
	/**
	 * @param itemObjUomSum the itemObjUomSum to set
	 */
	public void setItemObjUomSum(Integer value) {
		this.itemObjUomSum = value;
	}

	/**
	 * @return the itemRemark
	 */
	public String getItemRemark() {
		return this.itemRemark;
	}
	
	/**
	 * @param itemRemark the itemRemark to set
	 */
	public void setItemRemark(String value) {
		this.itemRemark = value;
	}

	/**
	 * @return the itemStatus
	 */
	public Integer getItemStatus() {
		return this.itemStatus;
	}
	
	/**
	 * @param itemStatus the itemStatus to set
	 */
	public void setItemStatus(Integer value) {
		this.itemStatus = value;
	}

	/**
	 * @return the itemType
	 */
	public Integer getItemType() {
		return this.itemType;
	}
	
	/**
	 * @param itemType the itemType to set
	 */
	public void setItemType(Integer value) {
		this.itemType = value;
	}

	/**
	 * @return the outId
	 */
	public String getOutId() {
		return this.outId;
	}
	
	/**
	 * @param outId the outId to set
	 */
	public void setOutId(String value) {
		this.outId = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnRentOutItem)) {
			return false;
		}
		PpnRentOutItem other = (PpnRentOutItem)o;
		if (null == this.itemId) {
			if (other.itemId != null)
				return false;
		} else if (!this.itemId.equals(other.itemId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}
	
}