
package jetsennet.jppn;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-04-22T12:53:13.019+08:00
 * Generated source version: 2.7.4
 * 
 */
 
public class FileOperaterService_FileOperaterService_Server{

    protected FileOperaterService_FileOperaterService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FileOperaterServiceImpl();
        String address = "http://192.168.213.125:8080/PPNCommonService/services/FileOperaterService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new FileOperaterService_FileOperaterService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
