package jetsennet.jppn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-04-22T12:53:13.013+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://JetsenNet/JPPN/", name = "FileOperaterService")
@XmlSeeAlso({jetsennet.jppn.bean.ObjectFactory.class, ObjectFactory.class})
public interface FileOperaterService {

    @WebResult(name = "out", targetNamespace = "http://JetsenNet/JPPN/")
    @RequestWrapper(localName = "fileOperation", targetNamespace = "http://JetsenNet/JPPN/", className = "jetsennet.jppn.FileOperation")
    @WebMethod
    @ResponseWrapper(localName = "fileOperationResponse", targetNamespace = "http://JetsenNet/JPPN/", className = "jetsennet.jppn.FileOperationResponse")
    public jetsennet.jppn.bean.JppnResult fileOperation(
        @WebParam(name = "objXml", targetNamespace = "http://JetsenNet/JPPN/")
        java.lang.String objXml
    );
}
