/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ppn.bean.PpnWslog.java
 * 日 期：Mon May 11 17:53:17 CST 2015
 */
package jetsennet.jcom.bean;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "PPN_WSLOG", keyGenerator = "uuid")
public class PpnWslog implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_WSLOG_CODE = "WSLOG_CODE";
	public static String PROP_WSLOG_CREATETIME = "WSLOG_CREATETIME";
	public static String PROP_WSLOG_FIELD1 = "WSLOG_FIELD1";
	public static String PROP_WSLOG_FIELD2 = "WSLOG_FIELD2";
	public static String PROP_WSLOG_ID = "WSLOG_ID";
	public static String PROP_WSLOG_METHODENAME = "WSLOG_METHODENAME";
	public static String PROP_WSLOG_SERVICENAME = "WSLOG_SERVICENAME";
	public static String PROP_WSLOG_SOURCEADDR = "WSLOG_SOURCEADDR";
	public static String PROP_WSLOG_SOURCESYS = "WSLOG_SOURCESYS";
	public static String PROP_WSLOG_TARGETADDR = "WSLOG_TARGETADDR";
	public static String PROP_WSLOG_TARGETSYS = "WSLOG_TARGETSYS";
	
	/** primary key field of wslogId */
	@FieldMapping(columnName = "WSLOG_ID", columnType = 12, primary = true)
	private String wslogId;
	@FieldMapping(columnName = "WSLOG_CODE", columnType = 12)
	private String wslogCode;
	@FieldMapping(columnName = "WSLOG_CREATETIME", columnType = 93)
	private Timestamp wslogCreatetime;
	@FieldMapping(columnName = "WSLOG_FIELD1", columnType = 12)
	private String wslogField1;
	@FieldMapping(columnName = "WSLOG_FIELD2", columnType = 12)
	private String wslogField2;
	@FieldMapping(columnName = "WSLOG_METHODENAME", columnType = 12)
	private String wslogMethodename;
	@FieldMapping(columnName = "WSLOG_SERVICENAME", columnType = 12)
	private String wslogServicename;
	@FieldMapping(columnName = "WSLOG_SOURCEADDR", columnType = 12)
	private String wslogSourceaddr;
	@FieldMapping(columnName = "WSLOG_SOURCESYS", columnType = 12)
	private String wslogSourcesys;
	@FieldMapping(columnName = "WSLOG_TARGETADDR", columnType = 12)
	private String wslogTargetaddr;
	@FieldMapping(columnName = "WSLOG_TARGETSYS", columnType = 12)
	private String wslogTargetsys;
	
	public PpnWslog() {
		super();
	}

	public PpnWslog(String wslogId) {
		this.wslogId = wslogId;
	}

	public PpnWslog(String wslogServicename, String wslogSourcesys, String wslogTargetsys) {
		this.wslogServicename = wslogServicename;
		this.wslogSourcesys = wslogSourcesys;
		this.wslogTargetsys = wslogTargetsys;
	}

	/**
	 * @return the wslogCode
	 */
	public String getWslogCode() {
		return this.wslogCode;
	}
	
	/**
	 * @param wslogCode the wslogCode to set
	 */
	public void setWslogCode(String value) {
		this.wslogCode = value;
	}

	/**
	 * @return the wslogCreatetime
	 */
	public Timestamp getWslogCreatetime() {
		return this.wslogCreatetime;
	}
	
	/**
	 * @param wslogCreatetime the wslogCreatetime to set
	 */
	public void setWslogCreatetime(Timestamp value) {
		this.wslogCreatetime = value;
	}

	/**
	 * @return the wslogField1
	 */
	public String getWslogField1() {
		return this.wslogField1;
	}
	
	/**
	 * @param wslogField1 the wslogField1 to set
	 */
	public void setWslogField1(String value) {
		this.wslogField1 = value;
	}

	/**
	 * @return the wslogField2
	 */
	public String getWslogField2() {
		return this.wslogField2;
	}
	
	/**
	 * @param wslogField2 the wslogField2 to set
	 */
	public void setWslogField2(String value) {
		this.wslogField2 = value;
	}

	/**
	 * @return the wslogId
	 */
	public String getWslogId() {
		return this.wslogId;
	}
	
	/**
	 * @param wslogId the wslogId to set
	 */
	public void setWslogId(String value) {
		this.wslogId = value;
	}

	/**
	 * @return the wslogMethodename
	 */
	public String getWslogMethodename() {
		return this.wslogMethodename;
	}
	
	/**
	 * @param wslogMethodename the wslogMethodename to set
	 */
	public void setWslogMethodename(String value) {
		this.wslogMethodename = value;
	}

	/**
	 * @return the wslogServicename
	 */
	public String getWslogServicename() {
		return this.wslogServicename;
	}
	
	/**
	 * @param wslogServicename the wslogServicename to set
	 */
	public void setWslogServicename(String value) {
		this.wslogServicename = value;
	}

	/**
	 * @return the wslogSourceaddr
	 */
	public String getWslogSourceaddr() {
		return this.wslogSourceaddr;
	}
	
	/**
	 * @param wslogSourceaddr the wslogSourceaddr to set
	 */
	public void setWslogSourceaddr(String value) {
		this.wslogSourceaddr = value;
	}

	/**
	 * @return the wslogSourcesys
	 */
	public String getWslogSourcesys() {
		return this.wslogSourcesys;
	}
	
	/**
	 * @param wslogSourcesys the wslogSourcesys to set
	 */
	public void setWslogSourcesys(String value) {
		this.wslogSourcesys = value;
	}

	/**
	 * @return the wslogTargetaddr
	 */
	public String getWslogTargetaddr() {
		return this.wslogTargetaddr;
	}
	
	/**
	 * @param wslogTargetaddr the wslogTargetaddr to set
	 */
	public void setWslogTargetaddr(String value) {
		this.wslogTargetaddr = value;
	}

	/**
	 * @return the wslogTargetsys
	 */
	public String getWslogTargetsys() {
		return this.wslogTargetsys;
	}
	
	/**
	 * @param wslogTargetsys the wslogTargetsys to set
	 */
	public void setWslogTargetsys(String value) {
		this.wslogTargetsys = value;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof PpnWslog)) {
			return false;
		}
		PpnWslog other = (PpnWslog)o;
		if (null == this.wslogId) {
			if (other.wslogId != null)
				return false;
		} else if (!this.wslogId.equals(other.wslogId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((wslogId == null) ? 0 : wslogId.hashCode());
		return result;
	}
	
}